### PR TITLE
update minio-go/v7 APIs again

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by BigUstad** [comment]
`mc ilm list --json s3alias/s3bucket`
There are some empty items in the JSON output, like:
`"NoncurrentVersionTransition": {},`
`"And": {},`

**Comment by BigUstad** [comment]
`mc ilm remove --id ere s3_2/pribkt3`
This rule is present, but the output is:
`mc: <ERROR> Unable to set lifecycle rules. The XML you provided was not well-formed or did not validate against our published schema.`

**Comment by harshavardhana** [comment]
> `mc ilm list --json s3alias/s3bucket`
> There are some empty items in the JSON output, like:
> `"NoncurrentVersionTransition": {},`
> `"And": {},`

These empty items are fine @BigUstad - they need to be ignored in minio-go custom Marshal

**Comment by harshavardhana** [comment]
> `mc ilm remove --id ere s3_2/pribkt3`
> This rule is present, but the output is:
> `mc: <ERROR> Unable to set lifecycle rules. The XML you provided was not well-formed or did not validate against our published schema.`

This one I found the problem @BigUstad its in minio-go

**Comment by harshavardhana** [comment]
> `mc ilm remove --id ere s3_2/pribkt3`
> This rule is present, but the output is:
> `mc: <ERROR> Unable to set lifecycle rules. The XML you provided was not well-formed or did not validate against our published schema.`

All issues fixed @BigUstad

**Pull request merged**
