### PR TITLE
Make mc ping useful for startup checks

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Add `--exit` parameter that will exit after first successful ping.

This makes `mc ping` much more useful to detect when a server has started.

## How to test this PR?

Play around with your local server.

```
λ go build&&mc ping -x -e 10 myminio
  1: http://127.0.0.1:9001:9001   min=1.37ms     max=1.37ms     average=1.37ms     errors=0   roundtrip=1.37ms

λ go build&&mc ping -x -e 10 myminio
  1: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=1   roundtrip=2.05s
  2: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=2   roundtrip=2.05s
  3: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=3   roundtrip=2.03s
  4: http://127.0.0.1:9001:9001   min=1.02s      max=1.02s      average=1.02s      errors=0   roundtrip=1.02s

λ go build&&mc ping -x -e 10 myminio
  1: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=1   roundtrip=2.03s
  2: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=2   roundtrip=2.05s
  3: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=3   roundtrip=2.03s
  4: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=4   roundtrip=2.04s
  5: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=5   roundtrip=2.04s
  6: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=6   roundtrip=2.04s
  7: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=7   roundtrip=2.04s
  8: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=8   roundtrip=2.02s
  9: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=9   roundtrip=2.05s
 10: http://127.0.0.1:9001:9001   min=0.00ms     max=0.00ms     average=0.00ms     errors=10  roundtrip=2.04s

λ _
```

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by klauspost** [comment]
@vadmeste It can't really be used to wait for the cluster to be up (without some scripting magic)

```
λ mc ready myminio
mc: <ERROR> Couldn't get the health status for `myminio`. Get "http://127.0.0.1:9001/minio/health/cluster": dial tcp 127.0.0.1:9001: connectex: No connection could be made because the target machine actively refused it.
λ 
```

**Comment by harshavardhana** [comment]
> @vadmeste It can't really be used to wait for the cluster to be up (without some scripting magic)
> 
> ```
> λ mc ready myminio
> mc: <ERROR> Couldn't get the health status for `myminio`. Get "http://127.0.0.1:9001/minio/health/cluster": dial tcp 127.0.0.1:9001: connectex: No connection could be made because the target machine actively refused it.
> λ 
> ```

This is actually a bug I think in the implementation, mc ping --exit-on-success is a good idea as well.

**Comment by klauspost** [comment]
`mc ping -x -e 60 myminio&&mc ready myminio` seems like the reasonable thing to wait for startup.

**Review by vadmeste — COMMENTED** [review]
LGTM

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
