### PR TITLE
cmd: Add encrypt to enable enc/decrypt objects

### LINKED ISSUE #2074: cp/mirror: [feature] bring mc transparent encryption
## Expected behaviour

Add a new sub-field for the aliases supporting transparent encryption.
```json
"encryption": {                                                                                                                                   
   "AES": {                                                                                                                                       
      "enable": true,                                                                                                                             
      "key": ""                                                                                                                                   
   },                                                                                                                                             
   "RSA": {                                                                                                                                       
      "enable": false,                                                                                                                            
      "publicKey": "/path/to/public.key",                                                                                                         
      "privateKey": "/path/to/private.key"
   },
}
```

There are no new flags are expected for mc. But a new command should be added. 

```
mc encrypt <alias> on
mc encrypt <alias> off
```

```
mc encypt <alias> on AES <optional_key>
```

```
mc encrypt <alias> on RSA <optional_public_key> <optional_private_key>
```

Not only does the above command enables encryption it should also either take input or generate symmetric/assymetric keys automatically for the user. So for a given alias if one of the encryptions are enabled all outgoing data to remote site is encrypted and all downloaded data is automatically decrypted. 

## Actual behaviour

No encryption support available

## mc version
master 

## System information
All platforms

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #2074

### CODE REVIEW

**Comment by harshavardhana** [comment]
Is this still a WIP @vadmeste ?

**Comment by vadmeste** [comment]
Yes, I made more simple changes, this PR can be reviewed now.

**Comment by harshavardhana** [comment]
> Also I need to think if we should add an API in minio-go which returns the real size of an object after being decrypted.

why is this needed?

**Comment by harshavardhana** [comment]
Keeping this waiting on @abperiasamy - its blocked to finalize the approach here.

**Comment by vadmeste** [comment]
The size of an object in encrypted form is different from the original size. mc compares the size of the downloaded data (data are clear because minio-go decrypts the stream on the fly) and finds that the size of the downloaded stream is different to the size of the same object in the server (using client-fs.Stat() primitive)

**Comment by bollig** [comment]
Any updates on this? Encrypt is a feature we're excited to leverage.

**Comment by harshavardhana** [comment]
@vadmeste after discussing with @abperiasamy - we decided that we don't need to do any config changes and it was simplified further. 

For the time being we will only support AES256 encryption on the client side which will also work with aes256-server when the server side implementation comes in.  Only commands which require this change are listed below.

```
- mc cp --encrypt-key=<key> --encrypt-type=aes256-server /etc/passwd myminio/bucket/
- mc cp -r --encrypt-key=<key> --encrypt-type=aes256 s3/bucket1/encrypted-objects myminio/bucket/encrypted-objects
- mc mirror --encrypt-key|-e=<key> --encrypt-type=aes256-server myminio/ s3/
- mc cat, mc pipe 
```
```
`-e` or `--encrypt-key` if has no key then we need to prompt on the command line. 
```

With this we can also support now FS to FS, FS to S3, S3 to FS decryption and encryption transparently.

**Comment by harshavardhana** [comment]
Unblocked this PR since we have finalized the approach.

**Comment by vadmeste** [comment]
mc mirror with encryption capability is weird because sometimes the size of encrypted object size is different to the size of plain representation. I'll investigate more.

**Comment by fwessels** [comment]
Have seen stuff like this before, has to do with working on blocks of eg 32 or 64 byte size (depending on algorithm) whereby the final block is likely to be padded with zeros. (And so the encrypted stream may be a little longer).

**Comment by vadmeste** [comment]
> Have seen stuff like this before, has to do with working on blocks of eg 32 or 64 byte size (depending on algorithm) whereby the final block is likely to be padded with zeros. (And so the encrypted stream may be a little longer).

Yes. But you can't know the exact length of the plain data from the length of encrypted data (you can with the reverse way). Though as you said padding will make the size of the encrypted data little longer (the maximum is the original size + block size).

I'll make the first step first then will see how to make this perfect.

**Comment by vadmeste** [comment]
Closing this in favor of https://github.com/minio/mc/pull/2197

**Pull request closed without merging**
