### PR TITLE
fix: support 'mc put --if-not-exists'

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix: support 'mc put --if-not-exists'

Also allow 'mc get --version-id'
## Motivation and Context
Just nice to have flags that have helped me 
to test things locally. 

## How to test this PR?
As mentioned in the PR

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
if-not-exists flag is currently hidden, until we decide to take full inputs like `--if-none-match`

**Comment by jiuker** [comment]
Please fix the lint or add `//nolint` at that line.

**Review by zveinn — APPROVED** [review]
LGTM, just remove the unused var.

**Review by klauspost — APPROVED** [review]
(yeah, or use it if it is supposed to be used)

**Pull request merged**
