### PR TITLE
Quote special characters in share curl command

### PR DESCRIPTION
**Pull request by supriyo-biswas**
See #3999 for the justification behind this change.

### CODE REVIEW

**Review by harshavardhana — COMMENTED** [review]
Please add unit tests for the function, that covers corner cases.

**Comment by supriyo-biswas** [comment]
Are we looking for testcases around `makeCurlCmd` or around `doShareUploadURL`?

**Comment by harshavardhana** [comment]
> Are we looking for testcases around `makeCurlCmd` or around `doShareUploadURL`?

makeCurlCmd, the regex part.

**Comment by klauspost** [comment]
Doesn't it work with URL escaped paths? Seems safer than escaping.

**Comment by supriyo-biswas** [comment]
As I understand URL-escaping is not a requirement of multipart/form-data requests. As a result, a file name of `foo $.pdf` is distinct from `foo%20%24.pdf` from Minio's perspective.

**Review by klauspost — APPROVED** [review]
👍🏼

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
