### PR TITLE
porting userCurrent from the minio project

### PR DESCRIPTION
**Pull request by arschles**
I accidentally closed https://github.com/minio/mc/pull/1533, so this replaces it with a single commit.

### CODE REVIEW

**Comment by arschles** [comment]
cc/ @harshavardhana

**Comment by harshavardhana** [comment]
This looks good to me. :+1:

**Comment by arschles** [comment]
@harshavardhana this doesn't look to be in `master` at https://github.com/minio/mc/blob/master/utils.go. did it get moved in a more recent commit?

**Comment by harshavardhana** [comment]
> @harshavardhana this doesn't look to be in master at https://github.com/minio/mc/blob/master/utils.go. did it get moved in a more recent commit?

Yes i created a comprehensive package pkg/user which 'mc' inherits now. and uses 'user.Current()' - https://github.com/minio/minio/tree/master/pkg/user

**Comment by arschles** [comment]
got it, thanks!

**Comment by harshavardhana** [comment]
> got it, thanks!

Your welcome!

**Comment by arschles** [comment]
@harshavardhana just an FYI, [three](https://github.com/deis/builder) [deis v2](https://github.com/deis/slugbuilder) [components](https://github.com/deis/minio) will be using `mc`, all in docker containers with `DOCKERIMAGE=1` set. In my testing it's been working very well.

I will be investigating whether it would be useful to run the minio server with that env variable set as well.

**Comment by harshavardhana** [comment]
> @harshavardhana just an FYI, three deis v2 components will be using mc, all in docker containers with DOCKERIMAGE=1 set. In my testing it's been working very well.
> 

That is great news, happy to help anytime if you face any issues - you can find us on https://gitter.im/minio/minio

> I will be investigating whether it would be useful to run the minio server with that env variable set as well.

You could use our official docker container.

**Pull request merged**
