### PR TITLE
support 'mc rm --non-current' to delete non-current objects

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by poornas** [comment]
It is either deleting delete-marker as well or fails altogether. 
```
➜  mc git:(83492653) mc ls dminio9/bucket --r --versions 
[2021-08-10 13:08:53 EDT]     0B e1f6c618-12a4-4448-8476-d384934f6452 v3 DEL A1
[2021-08-10 12:20:48 EDT]    26B 2977aebf-3c12-4003-bbce-3fa3652024b3 v2 PUT A1
[2021-08-10 12:20:43 EDT]    26B caa3c079-de3b-49ca-b799-966d14ed6be8 v1 PUT A1
[2021-08-10 12:20:47 EDT]    26B b86e111d-bee1-4aa6-a10f-5b83e5a93171 v2 PUT A2
[2021-08-10 12:20:46 EDT]    26B 9bc8aa69-324e-454d-b1bb-84b5851b36d4 v1 PUT A2
[2021-08-10 12:21:18 EDT]    26B 74b500c7-3eaa-4b63-ab4d-f0a3dc0ca4ad v1 PUT B1
[2021-08-10 12:21:25 EDT]     0B cd3cfd06-dc14-4a28-8350-16e108f84b8d v2 DEL B2
[2021-08-10 12:21:21 EDT]    26B d3022992-ef41-41f3-bd1d-eecb9818c501 v1 PUT B2
➜  mc git:(83492653) mc rm dminio9/bucket/B2 --non-current
mc: <ERROR> Failed to remove `dminio9/bucket/B2`. Object does not exist
➜  mc git:(83492653) mc rm dminio9/bucket/B2 --non-current --r --versions --force
Removing `dminio9/bucket/B2` (versionId=cd3cfd06-dc14-4a28-8350-16e108f84b8d, modTime=2021-08-10 16:21:25.314 +0000 UTC).
Removing `dminio9/bucket/B2` (versionId=d3022992-ef41-41f3-bd1d-eecb9818c501, modTime=2021-08-10 16:21:21.779 +0000 UTC).
➜  mc git:(83492653) mc ls dminio9/bucket --r --versions 
[2021-08-10 13:08:53 EDT]     0B e1f6c618-12a4-4448-8476-d384934f6452 v3 DEL A1
[2021-08-10 12:20:48 EDT]    26B 2977aebf-3c12-4003-bbce-3fa3652024b3 v2 PUT A1
[2021-08-10 12:20:43 EDT]    26B caa3c079-de3b-49ca-b799-966d14ed6be8 v1 PUT A1
[2021-08-10 12:20:47 EDT]    26B b86e111d-bee1-4aa6-a10f-5b83e5a93171 v2 PUT A2
[2021-08-10 12:20:46 EDT]    26B 9bc8aa69-324e-454d-b1bb-84b5851b36d4 v1 PUT A2
[2021-08-10 12:21:18 EDT]    26B 74b500c7-3eaa-4b63-ab4d-f0a3dc0ca4ad v1 PUT B1
➜  mc git:(83492653) 
```

**Comment by harshavardhana** [comment]
> It is either deleting delete-marker as well or fails altogether.
> 
> ```
> ➜  mc git:(83492653) mc ls dminio9/bucket --r --versions 
> [2021-08-10 13:08:53 EDT]     0B e1f6c618-12a4-4448-8476-d384934f6452 v3 DEL A1
> [2021-08-10 12:20:48 EDT]    26B 2977aebf-3c12-4003-bbce-3fa3652024b3 v2 PUT A1
> [2021-08-10 12:20:43 EDT]    26B caa3c079-de3b-49ca-b799-966d14ed6be8 v1 PUT A1
> [2021-08-10 12:20:47 EDT]    26B b86e111d-bee1-4aa6-a10f-5b83e5a93171 v2 PUT A2
> [2021-08-10 12:20:46 EDT]    26B 9bc8aa69-324e-454d-b1bb-84b5851b36d4 v1 PUT A2
> [2021-08-10 12:21:18 EDT]    26B 74b500c7-3eaa-4b63-ab4d-f0a3dc0ca4ad v1 PUT B1
> [2021-08-10 12:21:25 EDT]     0B cd3cfd06-dc14-4a28-8350-16e108f84b8d v2 DEL B2
> [2021-08-10 12:21:21 EDT]    26B d3022992-ef41-41f3-bd1d-eecb9818c501 v1 PUT B2
> ➜  mc git:(83492653) mc rm dminio9/bucket/B2 --non-current
> mc: <ERROR> Failed to remove `dminio9/bucket/B2`. Object does not exist
> ➜  mc git:(83492653) mc rm dminio9/bucket/B2 --non-current --r --versions --force
> Removing `dminio9/bucket/B2` (versionId=cd3cfd06-dc14-4a28-8350-16e108f84b8d, modTime=2021-08-10 16:21:25.314 +0000 UTC).
> Removing `dminio9/bucket/B2` (versionId=d3022992-ef41-41f3-bd1d-eecb9818c501, modTime=2021-08-10 16:21:21.779 +0000 UTC).
> ➜  mc git:(83492653) mc ls dminio9/bucket --r --versions 
> [2021-08-10 13:08:53 EDT]     0B e1f6c618-12a4-4448-8476-d384934f6452 v3 DEL A1
> [2021-08-10 12:20:48 EDT]    26B 2977aebf-3c12-4003-bbce-3fa3652024b3 v2 PUT A1
> [2021-08-10 12:20:43 EDT]    26B caa3c079-de3b-49ca-b799-966d14ed6be8 v1 PUT A1
> [2021-08-10 12:20:47 EDT]    26B b86e111d-bee1-4aa6-a10f-5b83e5a93171 v2 PUT A2
> [2021-08-10 12:20:46 EDT]    26B 9bc8aa69-324e-454d-b1bb-84b5851b36d4 v1 PUT A2
> [2021-08-10 12:21:18 EDT]    26B 74b500c7-3eaa-4b63-ab4d-f0a3dc0ca4ad v1 PUT B1
> ➜  mc git:(83492653) 
> ```

non-current doesn't work without  `--versions` and `--recursive` @poornas

**Comment by harshavardhana** [comment]
> > It is either deleting delete-marker as well or fails altogether.
> > ```
> > ➜  mc git:(83492653) mc ls dminio9/bucket --r --versions 
> > [2021-08-10 13:08:53 EDT]     0B e1f6c618-12a4-4448-8476-d384934f6452 v3 DEL A1
> > [2021-08-10 12:20:48 EDT]    26B 2977aebf-3c12-4003-bbce-3fa3652024b3 v2 PUT A1
> > [2021-08-10 12:20:43 EDT]    26B caa3c079-de3b-49ca-b799-966d14ed6be8 v1 PUT A1
> > [2021-08-10 12:20:47 EDT]    26B b86e111d-bee1-4aa6-a10f-5b83e5a93171 v2 PUT A2
> > [2021-08-10 12:20:46 EDT]    26B 9bc8aa69-324e-454d-b1bb-84b5851b36d4 v1 PUT A2
> > [2021-08-10 12:21:18 EDT]    26B 74b500c7-3eaa-4b63-ab4d-f0a3dc0ca4ad v1 PUT B1
> > [2021-08-10 12:21:25 EDT]     0B cd3cfd06-dc14-4a28-8350-16e108f84b8d v2 DEL B2
> > [2021-08-10 12:21:21 EDT]    26B d3022992-ef41-41f3-bd1d-eecb9818c501 v1 PUT B2
> > ➜  mc git:(83492653) mc rm dminio9/bucket/B2 --non-current
> > mc: <ERROR> Failed to remove `dminio9/bucket/B2`. Object does not exist
> > ➜  mc git:(83492653) mc rm dminio9/bucket/B2 --non-current --r --versions --force
> > Removing `dminio9/bucket/B2` (versionId=cd3cfd06-dc14-4a28-8350-16e108f84b8d, modTime=2021-08-10 16:21:25.314 +0000 UTC).
> > Removing `dminio9/bucket/B2` (versionId=d3022992-ef41-41f3-bd1d-eecb9818c501, modTime=2021-08-10 16:21:21.779 +0000 UTC).
> > ➜  mc git:(83492653) mc ls dminio9/bucket --r --versions 
> > [2021-08-10 13:08:53 EDT]     0B e1f6c618-12a4-4448-8476-d384934f6452 v3 DEL A1
> > [2021-08-10 12:20:48 EDT]    26B 2977aebf-3c12-4003-bbce-3fa3652024b3 v2 PUT A1
> > [2021-08-10 12:20:43 EDT]    26B caa3c079-de3b-49ca-b799-966d14ed6be8 v1 PUT A1
> > [2021-08-10 12:20:47 EDT]    26B b86e111d-bee1-4aa6-a10f-5b83e5a93171 v2 PUT A2
> > [2021-08-10 12:20:46 EDT]    26B 9bc8aa69-324e-454d-b1bb-84b5851b36d4 v1 PUT A2
> > [2021-08-10 12:21:18 EDT]    26B 74b500c7-3eaa-4b63-ab4d-f0a3dc0ca4ad v1 PUT B1
> > ➜  mc git:(83492653) 
> > ```
> 
> non-current doesn't work without `--versions` and `--recursive` @poornas

It also will not remove only `delete-markers` - it will only remove `non-current` versions along with their delete markers.

**Comment by poornas** [comment]
>It also will not remove only delete-markers - it will only remove non-current versions along with their delete markers.

In the example above, expected that v1 which is the non-current version would get deleted.  
`[2021-08-10 12:21:21 EDT]    26B d3022992-ef41-41f3-bd1d-eecb9818c501 v1 PUT B2`

**Comment by harshavardhana** [comment]
> In the example above, expected that v1 which is the non-current version would get deleted.
> `[2021-08-10 12:21:21 EDT] 26B d3022992-ef41-41f3-bd1d-eecb9818c501 v1 PUT B2`

Your V1 needs to have a delete marker first it's not all non-current versions it's non-current with the top-level version being a delete marker. 

The behavior is exactly similar to how ILM would expire non-current versions and it won't leave delete marker either @poornas

**Review by krisis — APPROVED** [review]

**Review by poornas — APPROVED** [review]

**Pull request merged**
