### PR TITLE
Move `admin speedtest` to `support perf`

### PR DESCRIPTION
**Pull request by anjalshireesh**
As part of reorganization of support related commands

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
@wlan0 @harshavardhana  was it decided to move `mc speedtest ..` to `mc support perf ...` ? If so what does the new command line arguments look like for object, drive, net? do you know?

**Comment by harshavardhana** [comment]
> @wlan0 @harshavardhana was it decided to move `mc speedtest ..` to `mc support perf ...` ? If so what does the new command line arguments look like for object, drive, net? do you know?

Yes

**Comment by anjalshireesh** [comment]
> @wlan0 @harshavardhana was it decided to move `mc speedtest ..` to `mc support perf ...` ? If so what does the new command line arguments look like for object, drive, net? do you know?

@krishnasrinivas Just the command is being moved from under `admin` to `support` and renamed from `speedtest` to `perf`. It's behavior, including command line arguments, should remain same.

**Comment by harshavardhana** [comment]
PTAL @anjalshireesh and resolve the conflicts.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
