### PR TITLE
Vendorize all the latest dependencies with go mod

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by kannappanr** [comment]
@harshavardhana PTAL at Travis failures

**Comment by wlan0** [comment]
Please update travis.yaml to use GOMODULES111=on. 

Please ensure that this builds with previous version of go as well.

**Comment by harshavardhana** [comment]
> Please update travis.yaml to use GOMODULES111=on.
> 
> Please ensure that this builds with previous version of go as well.

all of it fixed @wlan0

**Comment by donatello** [comment]
So in go 1.11 my understanding is that `$GOPATH` is no longer needed to manage deps - if this is the case, this PR is not building when GOPATH is not set. It builds in go 1.10 though.

**Comment by wlan0** [comment]
@donatello What is the value of the env var `GO111MODULE`

**Comment by harshavardhana** [comment]
> So in go 1.11 my understanding is that `$GOPATH` is no longer needed to manage deps - if this is the case, this PR is not building when GOPATH is not set. It builds in go 1.10 though.

GOPATH issue is fixed @donatello

**Pull request merged**
