### PR TITLE
Allow disabling multipart uploads

### PR DESCRIPTION
**Pull request by Furtchet**
Added MC_MULTIPART_DISABLE environment variable. This allows for cp and mirroring to S3 repositories that don't support a multipart upload, like https://github.com/joyent/s3-manta-bridge

### CODE REVIEW

**Comment by Furtchet** [comment]
I tried running `git rebase -i` to fix the .*main.go conflicts from https://github.com/minio/mc/blob/master/CONTRIBUTING.md but I might just have made it worse. Let me know if I should destroy my branch and commit again.

**Comment by harshavardhana** [comment]
Please rebase the PR also lets discuss this first in a Github issue @Furtchet , intentions are not clear to add this just for Manta Object Storage.

**Comment by Furtchet** [comment]
Thank you harshavardhana, I was unaware of the significance of the vendor directory. Also, next time I will start with an issue instead of a PR.

**Comment by Furtchet** [comment]
@balamurugana,

This was useful because the software I was doing a `mc mirror` to was https://github.com/joyent/s3-manta-bridge and it didn't support multipart uploads. Yes I know the better solution would be to improve s3-manta-bridge to support multipart but that was more difficult because manta doesn't support multipart upload (currently https://github.com/joyent/rfd/blob/master/rfd/0065/README.md). And maybe someone else would like this feature too.

**Pull request closed without merging**
