### PR TITLE
Stat: display Expires header if present

### PR DESCRIPTION
**Pull request by poornas**
Fixes : #2690

### CODE REVIEW

**Comment by kannappanr** [comment]
@poornas Can you please fix Travis failure

**Comment by poornas** [comment]
> @poornas Can you please fix Travis failure
This should go away once minio-go change is vendorized.

**Comment by poornas** [comment]
updated PR after vendorizing minio-go

**Comment by ebozduman** [comment]
There is one more place where `Expiry` needs to be set (line# 1076 in the old code)
```
			if isFetchMeta {
				stat, err := c.getObjectStat(bucket, object, opts)
				if err != nil {
					return nil, err
				}
				objectMetadata.ETag = stat.ETag
				objectMetadata.Metadata = stat.Metadata
				objectMetadata.EncryptionHeaders = stat.EncryptionHeaders
			}
```

**Comment by poornas** [comment]
> There is one more place where `Expiry` needs to be set (line# 1076 in the old code)
fixed @ebozduman

**Comment by poornas** [comment]
> We also need to add `Expiry` setting in our existing tests, like `TestParseStat` in stat_test.go
done

**Pull request merged**
