### PR TITLE
add support for watching for replication/ilm events

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by poornas** [comment]
need to add ilm events for transition from this PR https://github.com/minio/minio/pull/11047

**Comment by harshavardhana** [comment]
> need to add ilm events for transition from this PR [minio/minio#11047](https://github.com/minio/minio/pull/11047)

Transition events added @poornas

**Review by poornas — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
