### PR TITLE
Change Hombrew package name

### PR DESCRIPTION
**Pull request by OKNoah**
The Homebrew formulae website lists the app as "minio-mc".

### CODE REVIEW

**Comment by harshavardhana** [comment]
We don't recommend using Homebrew upstream mc, we recommend our repo 

https://github.com/minio/homebrew-stable 

So it is pointing to the right binary package. Is there a real reason to change this ?

**Comment by OKNoah** [comment]
@harshavardhana The command as written did not work. It suggested installing a tap, via `brew install minio/stable/mc`, but that too failed. In both cases it could not find such a formulae or tap.

Running `brew --version` gives me

```
Homebrew 2.0.0
Homebrew/homebrew-core (git revision cb293; last commit 2019-02-07)
Homebrew/homebrew-cask (git revision b406; last commit 2019-02-06)
```

**Comment by harshavardhana** [comment]
> @harshavardhana The command as written did not work. It suggested installing a tap, via `brew install minio/stable/mc`, but that too failed. In both cases it could not find such a formulae or tap.
> 
> Running `brew --version` gives me

Let me check if they changed the brew tap behavior.

**Comment by harshavardhana** [comment]
Just tested with latest brew 2.0.1 - I don't think this PR is needed we are working fine with our taps

Upgraded an old `mc` installation and worked fine
```
~  brew upgrade minio/stable/mc
==> Upgrading 1 outdated package:
minio/stable/mc 20171212010802Z_1 -> 20190213194827Z_1
==> Upgrading minio/stable/mc
==> Downloading https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.2019-02-13T19-48-27Z
######################################################################## 100.0%
🍺  /usr/local/Cellar/mc/20190213194827Z_1: 3 files, 17.3MB, built in 3 seconds
Removing: /usr/local/Cellar/mc/20170403183501_1... (3 files, 6.9MB)
Removing: /usr/local/Cellar/mc/20170615T033843Z_1... (3 files, 7.0MB)
Removing: /usr/local/Cellar/mc/20171014T005116Z_1... (3 files, 8.5MB)
Removing: /usr/local/Cellar/mc/20171212010802Z_1... (3 files, 8.5MB)
```

Will close this PR.

**Pull request closed without merging**
