### PR TITLE
Get speedtest results as part of `support diag`

### PR DESCRIPTION
**Pull request by anjalshireesh**
Also remove the `--full` flag and run the new perf tests (that run quite
fast) always (if the minio version supports it).

In case of older versions of minio that have the older versions of the
performance tests, mc will not request for those tests to be run, and
subsequently will not look for their results in the response.

### CODE REVIEW

**Comment by kannappanr** [comment]
ping @balamurugana

**Review by balamurugana — APPROVED** [review]

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Is there a server side for this change to be tested ?

**Comment by klauspost** [comment]
How useful are speedtests when it is on a running system? They will be quite noisy AFAICT.

**Comment by harshavardhana** [comment]
> How useful are speedtests when it is on a running system? They will be quite noisy AFAICT.

Since we freeze the incoming calls it was kind of decided we can run these during diagnostics in one call.

**Review by klauspost — APPROVED** [review]

**Comment by anjalshireesh** [comment]
> Is there a server side for this change to be tested ?

@harshavardhana yes, I have the code, but can send a PR only after this PR is merged as minio depends on mc and in this case requires this PR as well to compile.

**Comment by harshavardhana** [comment]
> > Is there a server side for this change to be tested ?
> 
> @harshavardhana yes, I have the code, but can send a PR only after this PR is merged as minio depends on mc and in this case requires this PR as well to compile.

Wait why would MinIO depend on mc ? Isn't it is madmin-go that needs to be updated here ?

**Comment by anjalshireesh** [comment]
> > > Is there a server side for this change to be tested ?
> > 
> > 
> > @harshavardhana yes, I have the code, but can send a PR only after this PR is merged as minio depends on mc and in this case requires this PR as well to compile.
> 
> Wait why would MinIO depend on mc ? Isn't it is madmin-go that needs to be updated here ?

@harshavardhana `minio` indirectly depends on `mc` through `console`:

mc -> console -> minio

The `minio` side changes for this feature fail compilation with following errors:

```
❯ make
Checking dependencies
Building minio binary to './minio'
# github.com/minio/mc/cmd
../../../../pkg/mod/github.com/minio/mc@v0.0.0-20220302011226-f13defa54577/cmd/support-diag.go:467:23: info.Perf.Drives undefined (type madmin.SpeedTestResults has no field or method Drives)
../../../../pkg/mod/github.com/minio/mc@v0.0.0-20220302011226-f13defa54577/cmd/support-diag.go:468:42: info.Perf.Net undefined (type madmin.SpeedTestResults has no field or method Net)
../../../../pkg/mod/github.com/minio/mc@v0.0.0-20220302011226-f13defa54577/cmd/support-diag.go:468:68: info.Perf.NetParallel undefined (type madmin.SpeedTestResults has no field or method NetParallel)
../../../../pkg/mod/github.com/minio/mc@v0.0.0-20220302011226-f13defa54577/cmd/support-diag.go:646:36: undefined: madmin.HealthDataTypesLite
make: *** [Makefile:87: build] Error 1
```

because the `mc` included in `minio` doesn't have the latest `madmin-go`.
The compilation should go through after merging this PR, including the latest `mc` in `console`, and updating the console dependency in `minio`.

**Comment by harshavardhana** [comment]
Correct but you can send a PR for server referencing this commit to be necessary to build. 

I can't test this PR right now without server side change.

**Comment by anjalshireesh** [comment]
> Correct but you can send a PR for server referencing this commit to be necessary to build.
> 
> I can't test this PR right now without server side change.

I've created a draft WIP PR here for testing: https://github.com/minio/minio/pull/14696

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by sinhaashish — APPROVED** [review]

**Pull request merged**
