### PR TITLE
mirror: Avoid session and enable continuous mirror

### PR DESCRIPTION
**Pull request by vadmeste**

### CODE REVIEW

**Comment by vadmeste** [comment]
Ready for review.

**Comment by felixbuenemann** [comment]
Enabling watch mode by default is imho a bad idea, it breaks existing scripts which depend on mirror exiting when it's done. It also looks like there's no way to disable watch mode.

**Comment by harshavardhana** [comment]
The breaking change was introduced on purpose and intentional is there a reason that you need this @felixbuenemann . For S3  mc would exit normally but for Minio it would start watching and wait.

**Comment by felixbuenemann** [comment]
> For S3 mc would exit normally but for Minio it would start watching and wait.

I tried mc mirror local_folder s3/my-bucket and it just sat there waiting for changes instead of exiting, which means mc mirror can no longer be used for scripting.

**Comment by harshavardhana** [comment]
> I tried mc mirror local_folder s3/my-bucket and it just sat there waiting for changes instead of exiting, which means mc mirror can no longer be used for scripting.

It is going to watch for FS on new events..

**Comment by felixbuenemann** [comment]
I know, and it should not, because it makes scripting impossible.

**Comment by felixbuenemann** [comment]
To be clear, it's fine for me to enable watch behavior with a switch, but it shouldn't be the default.

**Pull request merged**
