### PR TITLE
retention: Refactor and add support of versioning

### PR DESCRIPTION
**Pull request by vadmeste**
Implementing mc retention set/clear/info with --versions, --version-id, --rewind and --default flags.

### CODE REVIEW

**Comment by vadmeste** [comment]
The command spec is approved, this PR can be tested and reviewed now.

**Comment by vadmeste** [comment]
> PTAL build failures

Fixed

**Comment by vadmeste** [comment]
@kannappanr all your comments are addressed.

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
