### PR TITLE
Fix travis and some code formatting

### PR DESCRIPTION
**Pull request by vadmeste**

### CODE REVIEW

**Comment by vadmeste** [comment]
Looks like .travis was not checking source code formatting, can you check @harshavardhana ?

**Comment by harshavardhana** [comment]
> Looks like .travis was not checking source code formatting, can you check @harshavardhana ?

It does check @vadmeste you need to add the code that i mentioned from minio repo for it to fail.

**Comment by vadmeste** [comment]
> It does check @vadmeste you need to add the code that i mentioned from minio repo for it to fail.

yes, I meant there was a double problem, you can check the change in .travis

**Comment by harshavardhana** [comment]
@vadmeste but you already fixed the erroneous files :-)

**Pull request merged**
