### PR TITLE
Show mc version when building from source file

### PR DESCRIPTION
**Pull request by ruspaul013**
## Description
Showing mc version when building from source file.

## Motivation and Context
If mc is build form tar.gz file, when running minio --version will show
```
mc version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
Runtime: go1.23.0 linux/amd64
Copyright (c) 2015-0000 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```
With this commit, mc will show now
```
mc version CUSTOM.2024-09-16T17-43-14Z (commit-id=DEVELOPMENT.GOGET)
Runtime: go1.23.0 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## How to test this PR?
Download the tar.gz file, unzip the file and then run make, after that run `./mc --version`.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
Home-built binaries should not show as official releases.

**Comment by ruspaul013** [comment]
@klauspost  Instead of RELEASE, can be something else like CUSTOM?

**Comment by klauspost** [comment]
That seems reasonable.

**Comment by harshavardhana** [comment]
This requires that you passing MC_VERSION information, I don't see why we need this on our end. you want to build some custom binaries for `mc` do that in your own fork if needed.

**Pull request closed without merging**
