### PR TITLE
update to newer libraries

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
update to newer libraries

## Motivation and Context
just upgrade the deps

## How to test this PR?
Nothing special, nothing should break

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by poornas — APPROVED** [review]

**Comment by k4leung4** [comment]
with this PR, I'm having problems install minio/mc with go

`go install [github.com/minio/mc@latest](http://github.com/minio/mc@latest)` fails with 

```
go: downloading github.com/minio/mc v0.0.0-20230202165714-2679713ec403
go: github.com/minio/mc@latest (in github.com/minio/mc@v0.0.0-20230202165714-2679713ec403):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

`go install github.com/minio/mc@6e97f161c85b41548ae452e0681799fa072e5ffc` works fine

**Comment by harshavardhana** [comment]
For now just install via `make install` @k4leung4 - we need the replace directives because one of our dependent packages are broken.

**Comment by k4leung4** [comment]
ack, thank you.

**Pull request merged**
