### PR TITLE
reorganize ILM tier commands 

### PR DESCRIPTION
**Pull request by krisis**
## Description
This change aims to make the connection between tiering and ILM more obvious and discoverable.
This is in part done by moving `admin-tier` subcommands into `ilm-tier` subcommand hierarchy. Additionally, ILM rule CRUD operations are moved into `ilm-rule` subcommand to make the intent of those subcommands explicit.

Following example should help see the motivation for this change clearly.

- Add a lifecycle rule with a transition and a noncurrent version transition action for objects with prefix `doc/` in `mybucket`.
```shell                                                                                                                               
     $ mc ilm tier add minio myminio MINIOTIER-1 --endpoint https://warm-minio-1.com \                                          
         --access-key ACCESSKEY --secret-key SECRETKEY --bucket bucket1 --prefix prefix1                                        
                                                                                                                                    
     $ mc ilm rule add --prefix "doc/" --transition-days "90" --transition-tier "MINIOTIER-1" \                                 
         --noncurrent-transition-days "45" --noncurrent-transition-tier "MINIOTIER-1" \                                         
         myminio/mybucket/                                                                                                                          
```

## How to test this PR?
1. Find and test ILM subcommands under `mc ilm rule` against a local MinIO deployment
2. Find and test tiering related subcommands under `mc ilm tier`. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [x] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
```
Error: cmd/admin-tier-deprecated.go:22:5: `adminTierDepCmds` is unused (deadcode)
var adminTierDepCmds = []cli.Command{
    ^
Error: cmd/ilm-restore.go:54:5: `ilmRestoreCmd` is unused (deadcode)
var ilmRestoreCmd = cli.Command{
    ^
```

**Comment by krisis** [comment]
Thanks @klauspost!

**Comment by klauspost** [comment]
Just the messenger 😂

**Review by vadmeste — COMMENTED** [review]
One comment

**Comment by krisis** [comment]
PTAL @klauspost @vadmeste I have addressed your comments.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
