### PR TITLE
Add admin bucket info command

### PR DESCRIPTION
**Pull request by vadmeste**
Print bucket usage and configuration (encryption, policy, ILM, etc..)

e.g:

```
$ mc admin bucket info myminio/testbucket/
Usage:
      Total size: 17 MiB
   Objects count: 63
  Versions count: 63

Properties:
  Encryption: 
        Algorithm: AES256
        Key ID: 
  Versioning: Enabled
  LockConfiguration: 
    RetentionMode: GOVERNANCE
    Retention Until Date: 30DAYS
  Location: us-east-1
  Policy: readwrite
  ILM: Set
```

### CODE REVIEW

**Comment by harshavardhana** [comment]
Do what does mc stat do on the bucket ?

**Comment by vadmeste** [comment]
> Do what does mc stat do on the bucket ?

Yes, plus the bucket usage information. We might need to discuss this internally. I am not sure if this is the exact requirement.

**Comment by klauspost** [comment]
We have the time of the last partial update. Should we add that?

**Comment by harshavardhana** [comment]
PTAL at the conflicts @vadmeste

**Comment by vadmeste** [comment]
> We have the time of the last partial update. Should we add that?

I tried to do it, but it doesn't seem we have a last update of a particular bucket. Only when the scanner finished doing a scan. And it seems we already have that in the new mc admin scanner info command

**Review by poornas — APPROVED** [review]

**Pull request merged**
