### PR TITLE
fix: 'mc stat' should exit properly if server returns 503

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by vadmeste** [comment]
@harshavardhana can you elaborate what this PR fixes exactly ? I know there is another related PR in minio/minio but still it is not clear how this PR is related

**Comment by harshavardhana** [comment]
> @harshavardhana can you elaborate what this PR fixes exactly ? I know there is another related PR in minio/minio but still it is not clear how this PR is related

IT fixes a situation where `mc stat alias/bucket/obj` if it returns 503 that gets displayed - the reason for this is because it is skipped by `isURLPrefixExists()`  because this returns success instead.

**Comment by vadmeste** [comment]
I think you can remove isURLPrefixExists() overall. It is always called after url2Stat(), the latter returns success if the prefix exists as well, 'prefix' or 'prefix/'

I can send a PR if you want

**Review by klauspost — APPROVED** [review]

**Comment by harshavardhana** [comment]
> I think you can remove isURLPrefixExists() overall. It is always called after url2Stat(), the latter returns success if the prefix exists as well, 'prefix' or 'prefix/'
> 
> I can send a PR if you want

@vadmeste sure that can be done it's a larger change to look at

PTAL the referenced PR on for MinIO as we need to make a new release.

**Pull request closed without merging**
