### PR TITLE
Adapt new changes in StorageInfo

### PR DESCRIPTION
**Pull request by Praveenrajmani**
Related to the StorageInfo changes in https://github.com/minio/minio/pull/8003
This PR can be blocked until the madmin changes gets merged

### CODE REVIEW

**Comment by Praveenrajmani** [comment]
Resolved the conflicts - PTAL @harshavardhana @sinhaashish

**Comment by Praveenrajmani** [comment]
this PR can be tested by adding `replace github.com/minio/minio => ../minio` in the go,mod with the server changes checked out locally

**Comment by harshavardhana** [comment]
The go mod is not updated @Praveenrajmani can you do that ?

**Comment by Praveenrajmani** [comment]
Updated the go.mod. PTAL @harshavardhana @sinhaashish

**Comment by Praveenrajmani** [comment]
PTAL @harshavardhana

**Pull request merged**
