### PR TITLE
Add go mod support and update dependencies

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by wlan0** [comment]
I agree that we need to move on to go modules. People cloning this repo wont have this project working out of the box with just this update. 

The complete update is a part of my `mc admin monitor PR` (https://github.com/minio/mc/pull/2657) -  https://github.com/minio/mc/pull/2657/commits/4eaefb969c6196c55f0172bf07e894e10e36e192

**Comment by harshavardhana** [comment]
> I agree that we need to move on to go modules. People cloning this repo wont have this project working out of the box with just this update.

I don't see any issue what issue do you see with this PR @wlan0 ?

**Comment by harshavardhana** [comment]
Fixed all the vendor issues as well @wlan0 so it looked like

```
~ GO111MODULE=on go mod init
go: creating new go.mod: module github.com/minio/mc
go: copying requirements from vendor/vendor.json
```

**Comment by wlan0** [comment]
for people using go version <1.11, the build will fail. Same issue with the CI build failing for this PR

**Comment by wlan0** [comment]
LGTM

**Pull request merged**
