### PR TITLE
Large bucket support admin API Changes

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
There is one more pending change related to `mc admin info` which is currently WIP, once done will remove WIP

**Comment by harshavardhana** [comment]
updated the pr with `mc admin info` changes as well.

**Comment by harshavardhana** [comment]
Removed the support `admin info` UI changes, after discussing with @abperiasamy we will bring changes to `admin info` and other command line changes in a separate PR.

**Comment by harshavardhana** [comment]
PTAL @vadmeste @donatello

**Comment by vadmeste** [comment]
LGTM.. However @harshavardhana  can you rebase large bucket PR in Minio server so we can fully test this PR ?

**Pull request merged**
