### PR TITLE
combine STS, SVC accounts into access keys with or without expiration

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
combine STS, SVC accounts into access keys with or without expiration

## Motivation and Context
from an end-user point of view, they are no different

## How to test this PR?
Configure LDAP and perform all the necessary activities to create accounts
with or without expiration. Then, observe the pretty printed output.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by taran-p** [comment]
Would the inability to delete STS access keys be an issue with listing them together?

**Comment by donatello** [comment]
Also sts keys need tokens so I think there should be an indication like a type so that users don't go looking for them in apps or scripts (for an audit for example).

**Comment by harshavardhana** [comment]
Fundamentally they are all the same from an API point of view, the idea here is just to show them a hint. Adding an sts tag might be okay let me see if I can add it cleanly. 

The current UI is quite wrong we need to address it.

**Comment by harshavardhana** [comment]
> Would the inability to delete STS access keys be an issue with listing them together?

There is no API contract requiring that all access keys be allowed to be deleted. Service Accounts is our extended implementation in MinIO. We just chose to allow it, in AWS STS credentials do not have that feature so in MinIO we didn't implement a DELETE behavior 
for them either.

**Comment by harshavardhana** [comment]
Added STS differentiation

**Review by taran-p — APPROVED** [review]

**Review by donatello — APPROVED** [review]

**Pull request merged**
