### PR TITLE
fix: mirror --summary should work like -q

### PR DESCRIPTION
**Pull request by jiuker**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

fix: mirror --summary should work like -q

Or user must use `--summary` with `-q` to avoid incorrect `ProgressStatus`.

```shell
jiuker@MacBook-Pro mc % ./mc mirror --overwrite --retry --summary --skip-errors /Users/jiuker/workspace/go/src/pkg/mc /Users/jiuker/workspace/go/src/minio/stage/issueBucket
.../go/src/pkg/mc/testdata/localhost.crt: 68.04 MiB / 68.04 MiB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  64.99 MiB/s 1s
jiuker@MacBook-Pro mc % ./mc mirror --overwrite --retry --summary --skip-errors /Users/jiuker/workspace/go/src/pkg/mc /Users/jiuker/workspace/go/src/minio/stage/issueBucket -q
Total: 0 B, Transferred: 0 B, Speed: 0 B/s

```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by shtripat — APPROVED** [review]
lgtm

**Review by klauspost — APPROVED** [review]

**Review by klauspost — CHANGES_REQUESTED** [review]
Can't `--summary` operate independent of `-q`, so it displays progress AND prints the summary when done?

**Comment by jiuker** [comment]
> Can't `--summary` operate independent of `-q`, so it displays progress AND prints the summary when done?

Yes. See the test case.
```shell
jiuker@MacBook-Pro mc % ./mc mirror --overwrite --retry --summary --skip-errors /Users/jiuker/workspace/go/src/pkg/mc /Users/jiuker/workspace/go/src/minio/stage/issueBucket
.../go/src/pkg/mc/testdata/localhost.crt: 68.04 MiB / 68.04 MiB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  64.99 MiB/s 1s
jiuker@MacBook-Pro mc % ./mc mirror --overwrite --retry --summary --skip-errors /Users/jiuker/workspace/go/src/pkg/mc /Users/jiuker/workspace/go/src/minio/stage/issueBucket -q
Total: 0 B, Transferred: 0 B, Speed: 0 B/s

```
@klauspost

**Review by zveinn — APPROVED** [review]
lgtm

**Review by klauspost — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
