### PR TITLE
make UI changes to speedtest bring a more cleaner spinner

### PR DESCRIPTION
**Pull request by harshavardhana**
- Removes flickering of spinner
- Moves to a more maintained library bubbles spinner
- Adds better visual formatting for table output

### CODE REVIEW

**Comment by harshavardhana** [comment]
https://asciinema.org/a/13ntDQlL07wp4BIJboXbdlMby for the visual output @krishnasrinivas @kannappanr

**Comment by harshavardhana** [comment]
<script id="asciicast-462025" src="https://asciinema.org/a/462025.js" async></script>

**Comment by harshavardhana** [comment]
[asciicast](https://asciinema.org/a/462025)

**Comment by harshavardhana** [comment]
[asciicast](https://asciinema.org/a/462048) - This was the final UI decided.

**Review by poornas — APPROVED** [review]

**Pull request merged**
