### PR TITLE
Make sure to preserve region specific URLs

### PR DESCRIPTION
**Pull request by harshavardhana**
This is to ensure that restricted access
to certain buckets is allowed on certain
regions.

This is a continuation of last commit

### CODE REVIEW

**Comment by kannappanr** [comment]
@harshavardhana PTAL Travis build failure

**Comment by harshavardhana** [comment]
ping @vadmeste @kannappanr

**Comment by vadmeste** [comment]
@harshavardhana not clear which issue this PR will fix, can you elaborate?

**Comment by harshavardhana** [comment]
> @harshavardhana not clear which issue this PR will fix, can you elaborate?

It fixes an issue when there are most restrictions on a given access/secret key. 

```
mc config host add mys3 https://s3.us-west-1.amazonaws.com/ <access> <secret>
```

Should honor the region directly here @vadmeste

**Comment by harshavardhana** [comment]
ping @kannappanr

**Pull request merged**
