### PR TITLE
heal: More verbose information

### PR DESCRIPTION
**Pull request by vadmeste**
heal info now shows the list of all MinIO nodes and the status of disks,
OK, unformatted, healing with an estimation of the time of healing
completion. It also shows the tolerance of nodes/disks, meaning how many
nodes or disks we can turn off before losing read operation in the
cluster.

### CODE REVIEW

**Comment by klauspost** [comment]
@vadmeste Do you have some sample output?

**Comment by vadmeste** [comment]
@klauspost 

```
mc admin heal myminio1 --storage-class=standard
Servers status:
==============
Pool 1:
  localhost:9001: (Tolerance: 1)
  +  /tmp/xl/1 : HEALING
  |__ Estimated: 7 minutes 
  |__  Capacity: 18 GiB/340 GiB
  |__ Tolerance: 1

  localhost:9002: (Tolerance: 1)
  +  /tmp/xl/2 : OK
  |__  Capacity: 18 GiB/340 GiB
  |__ Tolerance: 1

  localhost:9003: (Tolerance: 1)
  +  /tmp/xl/3 : OK
  |__  Capacity: 18 GiB/340 GiB
  |__ Tolerance: 1

  localhost:9004: (Tolerance: 1)
  +  /tmp/xl/4 : OK
  |__  Capacity: 18 GiB/340 GiB
  |__ Tolerance: 1


Server Failure Tolerance:
========================
Pool 1:
   Tolerance : 1 server(s)
       Nodes : localhost:9003 localhost:9004 localhost:9001 localhost:9002

Summary:
=======
Objects Healed: 966/1,332 (72.5%), 474 MB/591 MB (80.1%)
Heal rate: 0 obj/s, 379 KiB/s
Estimated Completion: 7 minutes 
```

**Comment by klauspost** [comment]
I don't really understand the `(Tolerance: 1)`. Is that disks or servers?

**Comment by harshavardhana** [comment]
> I don't really understand the `(Tolerance: 1)`. Is that disks or servers?

I think it's server tolerance.

**Comment by vadmeste** [comment]
yes, 

```
  localhost:9004: (Tolerance: 1) <- server tolerance
  +  /tmp/xl/4 : OK
  |__  Capacity: 18 GiB/340 GiB
  |__ Tolerance: 1 <- disk tolerance
  
  ```

**Comment by klauspost** [comment]
Then add the "unit", ie `Tolerance: 1 server(s)`, `Tolerance: 1 disk(s)`.

**Comment by vadmeste** [comment]
> Then add the "unit", ie `Tolerance: 1 server(s)`, `Tolerance: 1 disk(s)`.

Done

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
