### PR TITLE
share: Presign objects under a dir prefix

### LINKED ISSUE #2204: 'share download endpoint/bucket/' without -r does not produce share links
Trying to `share remote/bucket/path` without `--recursive` does not produce presigned URL(s).

The documentation promises:
```
   3. Share all objects under this folder with 5 days expiry.
      $ mc share download --expire=120h s3/backup/
```

## Expected Behavior

Have bucket/test/data.txt existing.

    $ mc share download minio/bucket/test/

Should produce a shareable link to test/data.txt

## Current Behavior

Above command does nothing.

## Your Environment
mc:  2017-06-15T03:38:43Z
minio: minio/minio:latest (96c93972853d)

### PR DESCRIPTION
**Pull request by vadmeste**
From now on, when the user specifies to share a prefix which represents
a directory, all objects under that directory will be shared without
having to check for --recursive flag. If the latter is specified, all
objects in all subdirs will be shared.

Fixed #2204

### CODE REVIEW

**Comment by krisis** [comment]
@vadmeste, I have the following namespace,
```
➜  mc git:(r2215) mc ls -r s1/test
[2017-07-17 09:46:21 IST]   105B dir/obj1
[2017-07-17 09:46:21 IST]   105B dir/obj2
[2017-07-17 09:46:21 IST]   105B dir/obj3
[2017-07-17 09:46:21 IST]   105B dir/obj4
[2017-07-17 09:43:58 IST]   105B obj1
[2017-07-17 09:43:58 IST]   105B obj2
[2017-07-17 09:43:58 IST]   105B obj3
[2017-07-17 09:43:58 IST]   105B obj4
```
When I run `mc share download s1/test/dir` I don't see shared URLs of the objects under the prefix.
But when I run `mc share download s1/test/dir/` I see share URLs of all the objects under the prefix.
This may be due to how we treat alias+path in mc, but this seems a little odd to me from a usability point of view. If we decide to stick to the current implementation we need to update mc-share's usage message.
I.e,
```
OPTIONS:
  --recursive, -r                  Share all objects recursively.
```
and
```
  4. Share all objects under this folder and all its sub-folders with 5 days expiry.
      $ mc share download --recursive --expire=120h s3/backup/

```

**Comment by vadmeste** [comment]
@krisis, I fixed the issue now. Thanks

**Comment by vadmeste** [comment]
> @vadmeste The help message still needs to be changed.

There is nothing to update @krisis. --recursive will share all objects under the specified directory and its subdirs. Without --recursive, only objects directly located under the specified dir will be shared.

**Comment by vadmeste** [comment]
@krisis, help text updated. Please take a look again.

**Pull request merged**
