### PR TITLE
[WIP] Add --check-etag in cat command

### PR DESCRIPTION
**Pull request by vadmeste**
Waiting for the command approval.

This doesn't work with server encrypted objects since ETag is not close to the md5sum here.

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
We can also do this with `mc find` @vadmeste as a feature - like find me all corrupted objects.

**Comment by vadmeste** [comment]
> We can also do this with `mc find` @vadmeste as a feature - like find me all corrupted objects.

We can do this way:
```
mc find myminio/testbucket/ -exec "mc cat --check-etag {}" >/dev/null
```

I don't want to push this feature too much since --check-etag won't work with server side encrypted objects.

**Comment by abperiasamy** [comment]
Checking etag on the client side is an expensive operation.

**Comment by vadmeste** [comment]
> Checking etag on the client side is an expensive operation.

Yes, this is a feature more for debugging purposes.

**Comment by harshavardhana** [comment]
Let's close this, there is no scope for this at the moment - s3-check-md5 served its purpose.

**Pull request closed without merging**
