### PR TITLE
alias: `mc alias list` command outputs the alias information specified by MC_CONFIG_ENV_FILE

### LINKED ISSUE #5015: `mc alias ls` does not output aliases from environment variable`MC_CONFIG_ENV_FILE`
## Expected behavior
I expect alias from `MC_CONFIG_ENV_FILE` occurred in the output of `mc alias ls`
## Actual behavior
It did not but commands like `mc ls` works
## Steps to reproduce the behavior
```shell
echo 'MC_HOST_some=xxxxx' > /etc/mc.config
export MC_CONFIG_ENV_FILE=/etc/mc.config
mc alias list
```
## mc --version
mc version RELEASE.2024-07-31T15-58-33Z (commit-id=f0d2ad47084cf1fbda8f955e9c6f4ee5d9c1daec)
Runtime: go1.22.5 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

## System information
Linux dev006 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Also, since there's multiple file related to alias config, adding a field telling which file it is from would be helpful, like:
```
play
  URL       : https://play.min.io
  AccessKey : Q3AM3UQ867SPQQA43P2F
  SecretKey : zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  API       : S3v4
  Path      : auto
  Src:      /home/some-user/.mc/config.json
```

### PR DESCRIPTION
**Pull request by dormanze**
The output of the mc alias list command is optimized.

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix #5015

## How to test this PR?
echo "MC_HOST_minio-1=https://myAccessKey:mySecretAccessKey@minio-1.minio-headless.kube-system.svc.cluster.local:8989" > /home/paas/mymc.config
export MC_CONFIG_ENV_FILE=/home/paas/mymc.config
export MC_HOST_backup=https://myAccessKey:mySecretAccessKey@minio-0.minio-headless.kube-system.svc.cluster.local:8989

/home/paas/mc alias list

image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
LGTM

**Review by shtripat — APPROVED** [review]
lgtm

**Comment by klauspost** [comment]
Running lint check
cmd/alias-list.go:143: File is not `gofumpt`-ed (gofumpt)

**Comment by harshavardhana** [comment]
what is optimized in the output? - the title can be better worded.

**Pull request merged**
