### PR TITLE
Length check for alias

### PR DESCRIPTION
**Pull request by shtripat**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Alias name should be at least 2 characters long.

## Motivation and Context
Fixes: https://github.com/minio/mc/issues/4512

## How to test this PR?
`mc alias set a http://localhost:9000 minioadmin minioadmin`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by jiuker — APPROVED** [review]

**Comment by klauspost** [comment]
Remind me why an alias can't be 1 character?

**Comment by shtripat** [comment]
> Remind me why an alias can't be 1 character?

cmd/config.go#isValidAlias() checks against regex `^[a-zA-Z][a-zA-Z0-9-_]+$`

**Comment by klauspost** [comment]
@shtripat I am not doubting it is there. I am asking *why* is it there.

**Comment by shtripat** [comment]
> @shtripat I am not doubting it is there. I am asking _why_ is it there.

Oh ok.

> 
> Seems to me naming your clusters `a` and `b` would be nice.

If we agree, we can change the regex. I think this could have been done just to make sure we dont end up using nos like `1` or `2` as alias names. @harshavardhana thoughts?

**Comment by vadmeste** [comment]
It looks like we need to ask the guy who added it:

```
0bd1edfd8 config.go     (Anand Babu (AB) Periasamy 2015-12-19 22:11:06 -0800 150) // isValidAlias - Check if alias valid.
0bd1edfd8 config.go     (Anand Babu (AB) Periasamy 2015-12-19 22:11:06 -0800 151) func isValidAlias(alias string) bool {
0bd1edfd8 config.go     (Anand Babu (AB) Periasamy 2015-12-19 22:11:06 -0800 152)       return regexp.MustCompile("^[a-zA-Z][a-zA-Z0-9-]+$").MatchString(alias)
0bd1edfd8 config.go     (Anand Babu (AB) Periasamy 2015-12-19 22:11:06 -0800 153) }
```

**Comment by klauspost** [comment]
Just seems like a regex having an unintended side effect.

**Comment by minio-trusted** [comment]
> Just seems like a regex having an unintended side effect.

We can fix the regex and allow it.

**Review by klauspost — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Comment by feorlen** [comment]
@shtripat to clarify, you _can_ have a single char alias name, but only if that char is `[A-Za-z]` ?

**Comment by shtripat** [comment]
> @shtripat to clarify, you _can_ have a single char alias name, but only if that char is `[A-Za-z]` ? 

Yes, single char can be a-z Or A-Z and multi char char could be like hello123, myminio2 etc.

**Pull request merged**
