### PR TITLE
put: Add  --disable-multipart to make it easier to use.

### PR DESCRIPTION
**Pull request by llchry**
put: Add --md5 and --disable-multipart to make it easier to use.

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Add `--md5` and `--disable-multipart` for `mc put`  action

## Motivation and Context
Add `--md5` and `--disable-multipart` for `mc put`  action

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]

**Comment by klauspost** [comment]
@harshavardhana @vadmeste @llchry I suggest we hold off on `--md5`.

I have added [checksums to minio-go](https://github.com/minio/minio-go/pull/2002). While MD5 isn't a checksum in the same sense, it serves the same purpose. So it seems to me like `--checksum=MD5|CRC32|CRC32C|SHA1|SHA256` would be a more sensible parameter from a user perspective?

**Comment by llchry** [comment]
> @harshavardhana @vadmeste @llchry I suggest we hold off on `--md5`.
> 
> I have added [checksums to minio-go](https://github.com/minio/minio-go/pull/2002). While MD5 isn't a checksum in the same sense, it serves the same purpose. So it seems to me like `--checksum=MD5|CRC32|CRC32C|SHA1|SHA256` would be a more sensible parameter from a user perspective?



> @harshavardhana @vadmeste @llchry I suggest we hold off on `--md5`.
> 
> I have added [checksums to minio-go](https://github.com/minio/minio-go/pull/2002). While MD5 isn't a checksum in the same sense, it serves the same purpose. So it seems to me like `--checksum=MD5|CRC32|CRC32C|SHA1|SHA256` would be a more sensible parameter from a user perspective?

**Comment by llchry** [comment]
> @harshavardhana @vadmeste @llchry I suggest we hold off on `--md5`.
> 
> I have added [checksums to minio-go](https://github.com/minio/minio-go/pull/2002). While MD5 isn't a checksum in the same sense, it serves the same purpose. So it seems to me like `--checksum=MD5|CRC32|CRC32C|SHA1|SHA256` would be a more sensible parameter from a user perspective?

Great，that's exactly what I wanted.

**Comment by klauspost** [comment]
@llchry Just remove the MD5 part. I will do the checksum stuff, since it is a bit more involved. I will ping you on the PR when ready.

**Comment by llchry** [comment]
> @llchry Just remove the MD5 part. I will do the checksum stuff, since it is a bit more involved. I will ping you on the PR when ready.

it has been removed. thanks

**Review by klauspost — APPROVED** [review]

**Review by klauspost — CHANGES_REQUESTED** [review]
----

**Review by klauspost — APPROVED** [review]

**Comment by klauspost** [comment]
https://github.com/minio/mc/pull/5043 adds checksums across the deck.

**Pull request merged**
