### PR TITLE
Copy metadata during mirror/cp operation

### PR DESCRIPTION
**Pull request by poornas**
Fixes https://github.com/minio/minio/issues/5324
Fixes https://github.com/minio/minio-go/issues/885

metadata is not being copied during mirror and copy operation. Turn this back on,
while also filtering out custom xattr metadata set on file system that do not 
respect http header convention. 

minio-go converts this metadata to http headers by prepending the key with x-amz-meta. file system xattributes which will fail http header convention need to be filtered out.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Its not just mirror this would enable for cp as well.

**Comment by kannappanr** [comment]
@poornas Travis and Appveyor failed, PTAL

**Comment by poornas** [comment]
fixed build failures - Can be reviewed.

**Comment by poornas** [comment]
@donatello, PTAL.

**Pull request merged**
