### PR TITLE
Add commands to set, show and remove proxy

### PR DESCRIPTION
**Pull request by anjalshireesh**
## Description

`mc support proxy set|show|remove`

This can be used to configure the proxy to be used to communicate with SUBNET.

## Motivation and Context

Provide a simple high level command to configure proxy for SUBNET communication

## How to test this PR?

`mc support proxy set {alias} {proxy-url}`

should set the given proxy URL in the minio config `subnet proxy`

`mc support proxy show {alias}`

should print the configured proxy on screen.

`mc support proxy remove {alias}`

should remove the minio config `subnet proxy`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
PTAL @vadmeste @ebozduman 🙏🏽

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by vadmeste** [comment]
@anjalshireesh maybe the server needs to automatically use the proxy configuration to send webhook logs to Subnet as well. I can do that if you agree

**Comment by anjalshireesh** [comment]
> @anjalshireesh maybe the server needs to automatically use the proxy configuration to send webhook logs to Subnet as well. I can do that if you agree

@vadmeste it has been discussed to support proxy configuration in the webhooks feature also and copy the proxy being set using `mc support proxy set` to the subnet webhook.

**Comment by harshavardhana** [comment]
PTAL at the conflicts @anjalshireesh

**Review by ebozduman — CHANGES_REQUESTED** [review]
Don't we also need to make changes for `proxy` command to be supported by auto-completion?

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
