### PR TITLE
progress bar update on obj write failure

### LINKED ISSUE #3193: Attempt to overwrite an object in compliance mode fails with success
## Expected behavior
When `mc cp` attempt to overwrite an object protected by retention setting, regardless of the mode (governance or compliance), is rejected for any reason, mc returns the correct error message, and the progress bar does not show up at all.

## Actual behavior
First a clear and correct error message is displayed ,but it is followed by a complete progress bar, as if some copy has actually started and  completed successfully.

## Steps to reproduce the behavior
1. $ mc ls myminio/bucket
2. $ mc lock myminio/bucket
GOVERNANCE mode is enabled for 2d
3. $ mc cp /etc/issue myminio/bucket/
/etc/issue:              26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 3.26 KiB/s 0s
4. $ mc cp /etc/issue myminio/bucket/
mc: <ERROR> Failed to copy `/etc/issue`. Object is WORM protected and cannot be overwritten
/etc/issue:              26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 8.28 KiB/s 0s

## mc --version
$ mc --version
mc version DEVELOPMENT.2020-04-27T23-48-39Z

## System information
$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 MINIO_REGION="us-east-1" minio server /var/tmp/data

### PR DESCRIPTION
**Pull request by BigUstad**
Fixes #3193

### CODE REVIEW

**Comment by ebozduman** [comment]
@kannappanr, @BigUstad, 
I don't want to enlarge the scope of this PR, but the same problem happens also for `mc mv` command. 
```
$ mc mv myminio/delete-issue-newlylocked/issue myminio/delete-issue-newlylocked/issue1
...ue-newlylocked/issue:  26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 638 B/s 0s
mc: <ERROR> Failed to remove in `http://192.168.1.8:9000/delete-issue-newlylocked/issue`. Object is WORM protected and cannot be overwritten
```
Please let me know if you would like to address this one in a separate issue, or here in this PR?

**Comment by BigUstad** [comment]
> I can still reproduce the issue when a local filesystem directory is recursively copied into an object storage bucket set with default retention `"governance 3d"`:
> 
> ```
> $ mc cp -r /var/tmp/ownership mm3/bucket
> mc: <ERROR> Failed to copy `/var/tmp/ownership/issue`. Object is WORM protected and cannot be overwritten
> mc: <ERROR> Failed to copy `/var/tmp/ownership/file`. Object is WORM protected and cannot be overwritten
> ...tmp/ownership/issue:  26 B / 52 B ┃▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░┃ 4.50 KiB/s 0s
> ```

A partial failure is the best case scenario I've encountered as the progress bar gets updated and  can't be rolled back. I'll look further into it.

**Comment by BigUstad** [comment]
> > I can still reproduce the issue when a local filesystem directory is recursively copied into an object storage bucket set with default retention `"governance 3d"`:
> > ```
> > $ mc cp -r /var/tmp/ownership mm3/bucket
> > mc: <ERROR> Failed to copy `/var/tmp/ownership/issue`. Object is WORM protected and cannot be overwritten
> > mc: <ERROR> Failed to copy `/var/tmp/ownership/file`. Object is WORM protected and cannot be overwritten
> > ...tmp/ownership/issue:  26 B / 52 B ┃▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░┃ 4.50 KiB/s 0s
> > ```
> 
> A partial failure is the best case scenario I've encountered as the progress bar gets updated and can't be rolled back. I'll look further into it.

Also progress-bar output depends on the time taken to copy and refresh rate, so it is possible that output might differ for the same set of inputs.

**Comment by BigUstad** [comment]
> I see an issue when multiple files are copied (with a wild card):
> 
> ```
> $ ll /var/tmp/ownership/
> total 16
> drwxr-xr-x  2 ersan ersan 4096 May  1 20:18 ./
> drwxrwxrwt 27 root  root  4096 May  6 02:35 ../
> -r--r--r--  1 ab    ab      26 May  1 20:17 file
> -rw-r--r--  1 ab    ab      26 May  1 20:18 issue
> $ mc lock myminio/delete-issue-newlylocked/
> GOVERNANCE mode is enabled for 1d
> $ mc ls myminio/delete-issue-newlylocked/
> [2020-05-06 02:07:59 PDT]     26B issue
> [2020-05-06 02:17:52 PDT]     26B locked-comp
> $ mc stat myminio/delete-issue-newlylocked/
> Name      : issue
> Date      : 2020-05-06 02:07:59 PDT 
> Size      : 26 B   
> ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
> Type      : file 
> Metadata  :
>   Content-Type                       : application/octet-stream 
>   X-Amz-Object-Lock-Retain-Until-Date: 2020-05-07T09:07:59Z 
>   X-Amz-Object-Lock-Mode             : GOVERNANCE 
> 
> Name      : locked-comp
> Date      : 2020-05-06 02:17:52 PDT 
> Size      : 26 B   
> ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f 
> Type      : file 
> Metadata  :
>   Content-Type                       : application/octet-stream 
>   X-Amz-Object-Lock-Mode             : COMPLIANCE 
>   X-Amz-Object-Lock-Retain-Until-Date: 2020-05-09T09:17:52Z 
> $ mc cp /var/tmp/ownership/* myminio/delete-issue-newlylocked/
> mc: <ERROR> Failed to copy `/var/tmp/ownership/issue`. Object is WORM protected and cannot be overwritten
> /var/tmp/ownership/issue:     26 B / 52 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░┃ 2.14 KiB/s 0s
> $ mc ls myminio/delete-issue-newlylocked/
> [2020-05-06 04:18:36 PDT]     26B file
> [2020-05-06 02:07:59 PDT]     26B issue
> [2020-05-06 02:17:52 PDT]     26B locked-comp
> ```
> 
> As seen in the above `mc cp` output, the failure message for file `"issue"` is correct since its retention is set to `"compliance"` mode, however, the progress bar was supposed to be shown for the successfully copied file `"file"` instead of `"issue"` again.

IMO it is working as expected. The file `"issue"` is shown in progress bar to indicate the 'current' file that is being copied. That kind of granular control to take names off of progress bar if an error is encountered is not available. The progress bar does indicate a failure to copy in the latter section, so the user does know not all items weren't copied.

**Pull request merged**
