### PR TITLE
trie: use trie package in minio

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Comment by balamurugana** [comment]
Wait till https://github.com/minio/minio/pull/3729 merged.  Till then :-1:

**Comment by krishnasrinivas** [comment]
@balamurugana https://twitter.com/bradfitz/status/829858091340410880 :p

**Comment by balamurugana** [comment]
@krishnasrinivas   github is not a good review system :P

**Comment by balamurugana** [comment]
PR is ready for the review.

**Pull request merged**
