### PR TITLE
Add policy set command

### PR DESCRIPTION
**Pull request by donatello**
Companion to https://github.com/minio/minio/pull/8036

### CODE REVIEW

**Comment by kannappanr** [comment]
We need to add `mc policy unset` command to remove policies set for a user or a group

**Comment by kannappanr** [comment]
It will also be good to add a `info` command to `mc admin user` so that the current evaluated policy can be displayed

**Comment by donatello** [comment]
> It will also be good to add a info command to mc admin user so that the current evaluated policy can be displayed

Done!

> We need to add mc policy unset command to remove policies set for a user or a group

We can do this subsequently after discussion. Holding on this one.

**Comment by kannappanr** [comment]
@donatello You probably did not checkin code related to `adminUserInfoCmd`.

**Comment by donatello** [comment]
> @donatello You probably did not checkin code related to adminUserInfoCmd.

Oops! Fixed now.

**Pull request merged**
