### PR TITLE
Add Damerau Levenshtein algo to suggest more alternatives to mistyped…

### PR DESCRIPTION
**Pull request by vadmeste**
… commmands

### CODE REVIEW

**Comment by vadmeste** [comment]
$ mc cnfig
.. Did you mean one of these?  ‘config’ 
$ mc ca
.. Did you mean one of these?
        ‘cat’
        ‘cp’
$ mc m
.. Did you mean one of these?
        ‘mb’
        ‘mirror’
        ‘rm’

**Comment by vadmeste** [comment]
$ mc lss
Did you mean one of these?
        ‘ls’

**Comment by vadmeste** [comment]
$ mc sl
Did you mean one of these?
‘ls’

**Comment by harshavardhana** [comment]
LGTM.

**Pull request merged**
