### PR TITLE
Removes Windows prefix path adjustment for 'mc ls'

### LINKED ISSUE #3509: 'mc ls <path>' does not honor backslash at the end of path on Windows
On windows, minio client includes \ at the end of each directory listed by `mc --insecure ls <alias>/<bucket>`.

This causes lots of complications , e.g. I can't use the name of directory directly to list it's contents, e.g.
```
> mc ls play/zzzz\
> mc ls play/zzzz
[2020-11-26 08:20:21 CET]   21KiB ll.jpg
> mc ls play/zzzz/
[2020-11-26 08:20:21 CET]   21KiB ll.jpg
```
or
```
> mc ls play/testaaa
[2020-11-27 17:01:08 CET]      0B jenkins\
```
and I can't use `> mc ls play/testaaa/jenkins\`
because
```
> mc ls play/testaaa/jenkins\
mc.exe: <ERROR> Unable to list folder. Object name contains unsupported characters.
```

## Expected behavior
Expected behavior is to either not include the slash at the end of directory at all, on all platforms, or to be consistent with linux behavior and return `/` even on windows.
E.g. 
```
> mc ls play/testaaa
[2020-11-27 17:01:08 CET]      0B jenkins/
```
or 
```
> mc ls play/testaaa
[2020-11-27 17:01:08 CET]      0B jenkins
```

## Actual behavior
returning backslack at end of directory names, e.g. this
```
> mc ls play/testaaa
[2020-11-27 17:01:08 CET]      0B jenkins\
```

## Steps to reproduce the behavior

1. Run `mc ls play/testaaa` or any other example on windows using the minio client `mc.exe`

## mc --version
- mc version RELEASE.2020-09-18T00-13-21Z

## System information
Windows 10 Enterprise, Version 10.0.19041 Build 19041

### PR DESCRIPTION
**Pull request by ebozduman**
Fixes #3509 and replaces PR#3573

Tested for regression, and will do more testing to make sure there is no regression on other apis that depend on the changed code.

### CODE REVIEW

**Review by sinhaashish — APPROVED** [review]
Not able to test , as i dont have any windows machine otherwise code looks good to me.

**Comment by ebozduman** [comment]
@vadmeste 

Could you PTAL and review this PR?

**Comment by ebozduman** [comment]
@vadmeste 
PTAL!

**Review by vadmeste — COMMENTED** [review]
It looks good to me but let's have more reviews here

**Review by klauspost — APPROVED** [review]
LGTM

**Pull request merged**
