### PR TITLE
cleanup 'admin health' command

### PR DESCRIPTION
**Pull request by harshavardhana**
- do not reach out to subnet if no license is provided
  this is a breaking change for customers where subnet.min.io
  is not reachable such as no "internet" access.

- use a proper httpClient when reaching out to subnet
  with a 10sec timeout, and also support custom proxies
  with self-signed certs.

- also fix some error messages and cleanup help with correct
  wording and grammar.

### CODE REVIEW

**Review by anjalshireesh — COMMENTED** [review]
> do not reach out to subnet if no license is provided
this is a breaking change for customers where subnet.min.io
is not reachable such as no "internet" access.

Such customers can use the `--airgap` flag to generate the health report file.

**Comment by harshavardhana** [comment]
> Such customers can use the `--airgap` flag to generate the health report file.

This is a breaking change - I shall remove `--license` dependency instead move towards showing the users that they can use `--airgap`

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
> > Such customers can use the `--airgap` flag to generate the health report file.
> 
> This is a breaking change - I shall remove `--license` dependency instead move towards showing the users that they can use `--airgap`

@anjalshireesh removed license dependency.

**Review by anjalshireesh — APPROVED** [review]

**Pull request merged**
