### PR TITLE
Allow copying file onto itself

### PR DESCRIPTION
**Pull request by harshavardhana**
This allows encrypting an unencrypted file
using server side CopyObject API.

### CODE REVIEW

**Comment by harshavardhana** [comment]
> Tested this, copying file onto itself seems to be working in all cases except this.
> If mc cp is attempted on encrypted object without correct keys, the error message is misleading..
> 
> ```
> ➜  mc git:(0a4cc528) ✗ mc cp --insecure mymino/bucket1/issue  myminio/bucket1/issue
> mc: <ERROR> Failed to copy `https://10.1.1.2:9000/bucket1/issue`. Object does not exist
> ```

Yeah this is a local error message @poornas

**Comment by poornas** [comment]
can you remove the InvalidArgument on https://github.com/minio/mc/blob/master/cmd/client-s3.go#L649 ? 
If an encrypted object is copied onto itself without encryption keys, it will give a better error message of "Bad Request" rather than Object does not exist

**Comment by vadmeste** [comment]
@harshavardhana I don't understand, how we can use mc to copy a file into itself while disabling the encryption ? (I understand the idea but it doesn't seem it is already possible in practice using mc)

**Comment by harshavardhana** [comment]
> can you remove the InvalidArgument check on https://github.com/minio/mc/blob/master/cmd/client-s3.go#L649 ?
> If an encrypted object is copied onto itself without encryption keys, it will give a better error message of "Bad Request" rather than Object does not exist

oh yes sure @poornas

**Pull request merged**
