### PR TITLE
rename policy to anonymous command

### PR DESCRIPTION
**Pull request by harshavardhana**
although keep `policy` command hidden
for backward compatibility.

### CODE REVIEW

**Comment by harshavardhana** [comment]
PTAL @vadmeste @Praveenrajmani this has been already decided by @abperiasamy

**Comment by vadmeste** [comment]
Working fine for me. However there is some issues from the old code. I will send a PR separetely.

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
@Praveenrajmani PTAL ?

**Review by Praveenrajmani — APPROVED** [review]

**Comment by harshavardhana** [comment]
@ravindk89 FYI

**Comment by ravindk89** [comment]
Thanks - I can straight hide `mc policy` from the next-gen docs and mark it as deprecated -> use `mc anonymous`

**Pull request merged**
