### PR TITLE
simplify histograms, make it based on the server return

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
simplify histograms, make it based on the server return

## Motivation and Context
avoid making `mc` by hardcoded with server return

## How to test this PR?
```sh
~ mc stat play/builds

Name      : builds
Date      : 2024-05-12 11:29:25 PDT 
Size      : N/A    
Type      : folder 

Properties:
  Versioning: Un-versioned
  Location: us-east-1
  Anonymous: Enabled
  ILM: Disabled

Usage:
      Total size: 301 MiB
   Objects count: 313
  Versions count: 0

Object sizes histogram:
   189 object(s) BETWEEN_1024B_AND_1_MB
    21 object(s) BETWEEN_1024_B_AND_64_KB
     0 object(s) BETWEEN_10_MB_AND_64_MB
     0 object(s) BETWEEN_128_MB_AND_512_MB
   124 object(s) BETWEEN_1_MB_AND_10_MB
    65 object(s) BETWEEN_256_KB_AND_512_KB
    41 object(s) BETWEEN_512_KB_AND_1_MB
    62 object(s) BETWEEN_64_KB_AND_256_KB
     0 object(s) BETWEEN_64_MB_AND_128_MB
     0 object(s) GREATER_THAN_512_MB
     0 object(s) LESS_THAN_1024_B
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by klauspost** [comment]
A bit annoying we can't present it in size sorted order. I guess that would require either an addition to the data sent or hard-coding "known" values.

**Comment by harshavardhana** [comment]
> Maybe pre-code a sort order for the fields we "know".

Yeah if server sends it's correctly and madmin is able to give it back properly then sure it will be fine.

But for now this is most simpler from what I could think of.

**Comment by klauspost** [comment]
@harshavardhana It is a map, so we don't control order.

**Comment by harshavardhana** [comment]
> @harshavardhana It is a map, so we don't control order.

Correct we have to change the data structure.

**Review by poornas — APPROVED** [review]

**Pull request merged**
