### PR TITLE
mc removes incomplete downloads .part.minio when rm is invoked with --incomplete flag

### PR DESCRIPTION
**Pull request by vadmeste**

### CODE REVIEW

**Comment by harshavardhana** [comment]
Actually this could be implemented because 'Listing' already lists incomplete upload properly even for FS.

**Comment by vadmeste** [comment]
> Actually this could be implemented because 'Listing' already lists incomplete upload properly even for FS.

This is local FS and not Minio FS (if I understood you well)

**Comment by harshavardhana** [comment]
> This is local FS and not Minio FS (if I understood you well)

yes 'mc ls -I'  lists incompletely download files.

**Comment by harshavardhana** [comment]
what else is missing in this patch @vadmeste ?

**Comment by vadmeste** [comment]
This patch is updated so it will remove *.part.minio for incomplete downloaded files

**Comment by harshavardhana** [comment]
> This patch is updated so it will remove *.part.minio for incomplete downloaded files

Update the patch description, it doesn't reflect what the patch is doing.

**Comment by vadmeste** [comment]
:+1:

**Pull request merged**
