### PR TITLE
migrate tags to minio-go tags

### PR DESCRIPTION
**Pull request by harshavardhana**
- fix missing tag command autocompletion
- fix non-idiomatic usage of probe.NewError
- fix error messages and indentiation in help
  messages etc.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Keeping this PR here for reference for another PR make these necessary changes before our next release.

**Comment by BigUstad** [comment]
_$ mc tag list prihome9002/bkt1/smear-oil-casserole-dish_4.jpg
Name : smear-oil-casserole-dish_4.jpg_

Empty tags shown this way.

**Comment by harshavardhana** [comment]
> _$ mc tag list prihome9002/bkt1/smear-oil-casserole-dish_4.jpg Name : smear-oil-casserole-dish_4.jpg_
> 
> Empty tags shown this way.

when there are no tags, no tags are shown @BigUstad there is no point in erroring out IMO

**Comment by BigUstad** [comment]
> > _$ mc tag list prihome9002/bkt1/smear-oil-casserole-dish_4.jpg Name : smear-oil-casserole-dish_4.jpg_
> > Empty tags shown this way.
> 
> when there are no tags, no tags are shown @BigUstad there is no point in erroring out IMO

Thank you.

**Comment by harshavardhana** [comment]
Will be merging changes here with @balamurugana PR

**Pull request closed without merging**
