### PR TITLE
Fix Windows config path

### LINKED ISSUE #2896: mc config is placed differently if mc.exe is used on Windows
It seems that mc config is placed based on the invocation command. That is unexpected on Windows.

## Expected Behavior

`mc config host list` and `mc.exe config host list` should read from the same place.

## Current Behavior

Config is placed in `mc` and `mc.exe` folders respectively.

## Possible Solution

It should probably be fine to just trim off `.exe`, or any extension in general. I don't see this as an issue that could be relevant elsewhere.

## Steps to Reproduce (for bugs)

See above

## Context

Having consistent config on my system.

## Regression

No

## Your Environment

* Version used (`minio version`): mc latest master
* Environment name and version (e.g. nginx 1.9.1): Commandline
* Operating System and version (`uname -a`): Win10, 64bit.

### PR DESCRIPTION
**Pull request by klauspost**
Remove '.exe' (case insensitive) from executable name for consistent config folder.

Potentially breaking: If people (for whatever reason) used 'mc.exe', this will potentially break their setup. No easy fix for that setup, especially since people could have both.

Fixes #2896

### CODE REVIEW

**Comment by harshavardhana** [comment]
We should add the migration code in `config-migrate.go`

```
// migrate config files from the any older version to the latest.
func migrateConfig() {
        // Migrate config V1 to V101
        migrateConfigV1ToV101()
        // Migrate config V101 to V2
        migrateConfigV101ToV2()
        // Migrate config V2 to V3
        migrateConfigV2ToV3()
        // Migrate config V3 to V4
        migrateConfigV3ToV4()
        // Migrate config V4 to V5
        migrateConfigV4ToV5()
        // Migrate config V5 to V6
        migrateConfigV5ToV6()
        // Migrate config V6 to V7
        migrateConfigV6ToV7()
        // Migrate config V7 to V8
        migrateConfigV7ToV8()
        // Migrate config V8 to V9
        migrateConfigV8ToV9()
        // Migrate config location on windows
        fixConfigLocation()
}
```

**Comment by klauspost** [comment]
Yeah. I guess we can overwrite it with the current invocation type. Lemme see what I can cook up.

**Comment by klauspost** [comment]
Tests. You can track directories by their timestamp.
```
λ go build && dir c:\users\klaus\mc* && mc config host list && dir c:\users\klaus\mc*
 Directory of c:\users\klaus                                                         
                                                                                     
05/09/2019  18.17    <DIR>          mc                                               
26/09/2019  13.46    <DIR>          mc.exe                                           
               0 File(s)              0 bytes                                        
               2 Dir(s)  201.392.041.984 bytes free                                  
[....]                                                                                     
 Directory of c:\users\klaus                                                         
                                                                                     
05/09/2019  18.17    <DIR>          mc                                               
26/09/2019  13.46    <DIR>          mc.unused                                        
               0 File(s)              0 bytes                                        
               2 Dir(s)  201.392.041.984 bytes free                                  
```
Called without .exe, config renamed `mc.exe` -> `mc.unused`. Calling again does nothing.

Calling with .exe and no .exe folder, nothing happens:

```
c:\gopath\src\github.com\minio\mc (fix-windows-config-path -> origin)                   
λ go build && dir c:\users\klaus\mc* && mc.exe config host list && dir c:\users\klaus\mc
 Directory of c:\users\klaus                                                            
                                                                                        
05/09/2019  18.17    <DIR>          mc                                                  
26/09/2019  13.46    <DIR>          mc.unused                                           
               0 File(s)              0 bytes                                           
               2 Dir(s)  201.391.525.888 bytes free                                     
[....]
 Directory of c:\users\klaus                                                            
                                                                                        
05/09/2019  18.17    <DIR>          mc                                                  
26/09/2019  13.46    <DIR>          mc.unused                                           
               0 File(s)              0 bytes                                           
               2 Dir(s)  201.391.525.888 bytes free                                     
```

Calling with `.exe` will move the bare `mc` folder to `mc.unused` and move `mc.exe` to `mc`:

```
λ go build && dir c:\users\klaus\mc* && mc.exe config host list && dir c:\users\klaus\mc*
 Directory of c:\users\klaus                                                             
                                                                                         
05/09/2019  18.17    <DIR>          mc                                                   
26/09/2019  13.46    <DIR>          mc.exe                                               
               0 File(s)              0 bytes                                            
               2 Dir(s)  201.445.535.744 bytes free                                      
[...]                                                                                         
 Volume in drive C is OS                                                                 
 Volume Serial Number is 5C65-5220                                                       
                                                                                         
 Directory of c:\users\klaus                                                             
                                                                                         
26/09/2019  13.46    <DIR>          mc                                                   
05/09/2019  18.17    <DIR>          mc.unused                                            
               0 File(s)              0 bytes                                            
               2 Dir(s)  201.445.535.744 bytes free                                      
```

Finally, if called with `.exe` and there is no folder without extension it is simply renamed `mc.exe` -> `mc`:

```
λ go build && dir c:\users\klaus\mc* && mc.exe config host list && dir c:\users\klaus\mc* 
 Directory of c:\users\klaus                                                              
                                                                                          
26/09/2019  13.46    <DIR>          mc.exe                                                
05/09/2019  18.17    <DIR>          mc.unused                                             
               0 File(s)              0 bytes                                             
               2 Dir(s)  201.447.510.016 bytes free                                       
[....]
 Directory of c:\users\klaus                                                              
                                                                                          
26/09/2019  13.46    <DIR>          mc                                                    
05/09/2019  18.17    <DIR>          mc.unused                                             
               0 File(s)              0 bytes                                             
               2 Dir(s)  201.447.510.016 bytes free                                       
                                                                                          
```

**Comment by klauspost** [comment]
@harshavardhana Updated with config location migration. 😅💦 

I rename the unused config instead of just deleting it.

**Comment by kannappanr** [comment]
ping @harshavardhana @vadmeste

**Comment by kannappanr** [comment]
@klaus PTAL Github action failures.

**Comment by harshavardhana** [comment]
> @klaus PTAL Github action failures.

The issue was related to GitHub server-side bug.

**Comment by audunmg** [comment]
When the executable is in the user's home folder (c:\users\audunmg\mc.exe) this renames the executable mc.exe to mc.unused or mc, and fails.

**Pull request merged**
