### PR TITLE
add 'mc admin trace' filtering based on request queries

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
add 'mc admin trace' filtering based on request queries

## Motivation and Context
a new feature based on the similar idea of `--request-header`

## How to test this PR?
`mc admin trace myminio/ --request-query max-keys=2` 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by feorlen** [comment]
@klauspost I'm not sure what `max-keys=2` means in your example command. What are some possible values and what should I expect to see?

I tried running this against `play` but didn't get any results. Would be nice to include a working example in the docs for this.

**Comment by harshavardhana** [comment]
> @klauspost I'm not sure what `max-keys=2` means in your example command. What are some possible values and what should I expect to see?
> 
> I tried running this against `play` but didn't get any results. Would be nice to include a working example in the docs for this.

A working example is mostly for rare situations where we have to debug an application.

You won't see this mc because mc never uses max-keys=2 

I don't think this needs public documentation, it is hardly useful for our customers.

People who are enthusiastic will learn it if needed but it is just a distraction for public facing docs. It is okay to skip this IMO.

**Comment by feorlen** [comment]
So this is intended for MinIO eng use? It's shown in the command help, which usually means it gets docs. Could we hide it in the help?

(Maybe this applies to `--request-header` as well? It has similarly vague and not helpful help text.)

**Comment by harshavardhana** [comment]
> So this is intended for MinIO eng use? It's shown in the command help, which usually means it gets docs. Could we hide it in the help?
> 
> (Maybe this applies to `--request-header` as well? It has similarly vague and not helpful help text.)

No it's okay, we don't need to hide. We want it discoverable for our folks as well.

**Pull request merged**
