### PR TITLE
Add --rewind flag for cat command

### PR DESCRIPTION
**Pull request by vadmeste**
It is possible to go back in time and download a specific version of 
an objet using mc cat --rewind command.

### CODE REVIEW

**Comment by poornas** [comment]
1. Can we add an example of --rewind flag usage on cli help also?
2. should we be issuing better error messages when --rewind flag is used on unversioned object or object created more recently than the duration specified in --rewind flag.
```
➜ mc cat --rewind 1m myminio/test/issue
mc: <ERROR> Unable to read from `myminio/test/issue`. Object does not exist.
``` 
maybe just show the contents if object created before time specified OR issue an error message that object is newer than duration specified. In the case of unversioned object, even if it was created within time window specified in --rewind, the error reported is `Object does not exist`. This will be misleading to user.

**Comment by vadmeste** [comment]
> 1. Can we add an example of --rewind flag usage on cli help also?

Sure

> 2\. should we be issuing better error messages when --rewind flag is used on unversioned object or object created more recently than the duration specified in --rewind flag.

I see --rewind flag like going back to time. I think object not found error makes sense here.

> In the case of unversioned object, even if it was created within time window specified in --rewind, the error reported is `Object does not exist`

This looks like a bug. Will investigate it.

**Comment by vadmeste** [comment]
> In the case of unversioned object, even if it was created within time window specified in --rewind, the error reported is `Object does not exist`

@poornas, I wasn't able to reproduce this, could you check again and tell me how to reproduce ?

**Comment by poornas** [comment]
> > In the case of unversioned object, even if it was created within time window specified in --rewind, the error reported is `Object does not exist`
> 
> @poornas, I wasn't able to reproduce this, could you check again and tell me how to reproduce ?

@vadmeste, I tested again - the object was more recent than the rewind duration specified. It shows contents for unversioned object too.

**Comment by vadmeste** [comment]
I also added a more descriptive error:

```
mc: <ERROR> Unable to read from `s3/vadmeste-testsnap/D`. Object did not exist at `Sat, 16 Mar 2019 20:33:38 CET`.   
```

**Pull request merged**
