### PR TITLE
Add new heal command

### LINKED ISSUE #1921: admin: Implement heal command
## Expected behaviour
Having a heal command to list buckets/objects that need to be healed and effectively heal them.

## Actual behaviour
Not having heal command

## mc version
All
## System information
All

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #1921

### CODE REVIEW

**Comment by harshavardhana** [comment]
What we also need is a fake option

```mc admin heal --fake --recursive alias``` 

heals '`format.json``, ``buckets`` and then subsequently ``objects`` 

Otherwise 

```mc admin heal --fake alias``` only attempts to heal `format.json` you will have to manually provide buckets that needs to be healed.  Closer analogy to borrow from is to think like `fsck` 

```
$ fsck
Phase 1 (metadata)
Phase 2 (directories)
Phase 3 (inodes)
``` 

```mc admin heal --fake --recursive alias/bucket/prefix``` would heal everything inside `prefix`.

**Comment by harshavardhana** [comment]
We do not need a sub command `repair`

**Comment by harshavardhana** [comment]
Can this is rebased @vadmeste - since healing code on server side is merged..

**Comment by vadmeste** [comment]
> Can this is rebased @vadmeste - since healing code on server side is merged..

I need to add --fake flag and other stuffs that you described earlier in this issue.

I just wanted to confirm, we'll remove repair command and keep list command ?

**Comment by harshavardhana** [comment]
> I just wanted to confirm, we'll remove repair command and keep list command ?

Yes 'repair' is not needed..

**Comment by vadmeste** [comment]
This is ready for review:

The only missing thing is healing format which is not ready yet in madmin package.

Also, when a bucket is specified in argument, I just heal it directly. ListBucketsHeal() is only called in heal list command when bucket is not specified, like `mc admin heal list myminio/`

**Pull request merged**
