### PR TITLE
replication diff: add header

### PR DESCRIPTION
**Pull request by poornas**
## Motivation and Context
https://github.com/minio/mc/issues/4286
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by harshavardhana** [comment]
what is the new format ? @poornas can you provide a snippet

**Comment by poornas** [comment]
```
➜  minio git:(master) mc replicate diff sitea/bucket --v
Replication Attempt At  | Created                 | Status    | VersionID                            | Op  | Object
2022-10-14 21:17:37 UTC | 2022-10-14 21:17:36 UTC | COMPLETED | 9765861b-e15a-4fa5-a5a1-2ee4b010f6f3 | PUT | sbin/ModemManager
                        | 2022-10-14 21:17:46 UTC | COMPLETED | 19f14bff-b894-4226-81fb-9f6f4dfa13d5 | DEL | sbin/ModemManager
2022-10-14 21:17:36 UTC | 2022-10-14 21:17:36 UTC | COMPLETED | 1339985a-4522-446c-9f8e-91f0e078c28e | PUT | sbin/a2dissite
                        | 2022-10-14 21:17:46 UTC | COMPLETED | 7a8cd1d7-97af-4710-a1f0-9539fd665244 | DEL | sbin/a2dissite
2022-10-14 21:17:37 UTC | 2022-10-14 21:17:36 UTC | COMPLETED | b177ca3c-f3d0-4997-8593-f45ae78ab8af | PUT | sbin/a2enconf
                        | 2022-10-14 21:17:46 UTC | COMPLETED | fbd55e07-9c1c-4ca9-b387-c24908a1bc34 | DEL | sbin/a2enconf
2022-10-14 21:17:37 UTC | 2022-10-14 21:17:36 UTC | COMPLETED | e562b73d-998c-4912-84c0-ff622b7f3db4 | PUT | sbin/a2ensite
                        | 2022-10-14 21:17:46 UTC | COMPLETED | daa40a03-0216-4360-ab79-d9cd1a4915e9 | DEL | sbin/a2ensite
2022-10-14 21:17:37 UTC | 2022-10-14 21:17:36 UTC | COMPLETED | 42f6927b-430e-485e-ae69-4bc3f425da8d | PUT | sbin/a2query
                        | 2022-10-14 21:17:46 UTC | COMPLETED | a767a824-c732-43e9-86c9-0f0df420970a | DEL | sbin/a2query
2022-10-14 21:17:37 UTC | 2022-10-14 21:17:36 UTC | COMPLETED | affef96e-2118-4b5c-a68a-b48dc9917ecd | PUT | sbin/aa-teardown
                        | 2022-10-14 21:17:46 UTC | COMPLETED | 2f6ce868-7296-4dd1-bb11-5c8a0cf760ce | DEL | sbin/aa-teardown
2022-10-14 21:17:37 UTC | 2022-10-14 21:17:37 UTC | COMPLETED | f85ea0dd-8f72-4959-ad49-5ecb564009eb | PUT | sbin/addgnupghome
```

**Comment by harshavardhana** [comment]
> Replication Attempt At  | Created                 | Status    | VersionID                            | Op  | Object

AttempedAt - is enough instead of "Replication" since it is `replicate diff`

**Comment by harshavardhana** [comment]
Also can you try using a more prettier table from bubbles project?

**Comment by poornas** [comment]
> Also can you try using a more prettier table from bubbles project?

Will explore that after this PR is merged

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
