### PR TITLE
stat:stat not work on windows

### LINKED ISSUE #4453: mc stat only works when using the "--recursive" flag on Windows
## Expected behavior
mc stat should not need the "--recursive" flag to perform the action on a file.
## Actual behavior
mc stat only works when using the "--recursive" flag
```
PS C:\Users\Administrator\Desktop> .\mc.exe stat play/testv/test.rtf --insecure
mc.exe: <ERROR> Unable to stat `play/testv/test.rtf`. Target `play/testv/test.rtf` not found.
PS C:\Users\Administrator\Desktop> .\mc.exe stat play/testv/test.rtf --insecure --recursive
Name      : test.rtf
Date      : 2023-01-23 12:49:18 CET
Size      : 7 B
ETag      : 8274425de767b30b2fff1124ab54abb5
Type      : file
Metadata  :
  Content-Type: text/rtf
```
## Steps to reproduce the behavior
Upload a file to a MinIO server (play.min.io also works for this) and try to do a stat on it while using a Windows client.
## mc --version
mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
Runtime: go1.19.4 windows/amd64
## System information
Client: Windows Server 2019 Standard in a VM environment
MinIO Server: tested on play.min.io and local Linux VM

### PR DESCRIPTION
**Pull request by dormanze**
## Description
fix #4453 

## Motivation and Context
The PR #3614  modification causes the split line processing problem in the Windows scenario.The separator needs to be processed uniformly.

### On a Windows host:
```
$ ./mc.exe ls myminio/
[2023-02-27 16:06:41 CST]     0B test/
[2023-02-27 16:17:11 CST]     0B test1/
[2023-02-27 16:17:42 CST]     0B test2/

$ ./mc.exe  stat myminio/test2/mc
Name      : mc
Date      : 2023-02-27 16:17:59 CST
Size      : 34 MiB
ETag      : 3c76065ff074d06bac19c0747ddc182f-3
Type      : file
Metadata  :
  Content-Type: application/x-executable

```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by klauspost** [comment]
It seems like this is an area where fixing one issue regresses 10 others.

This code is used by `ls`, `rm`, `undo`, `legalhold ...`, `retention ...`, so I am a bit worried this can cause regressions there.

**Comment by dormanze** [comment]
> It seems like this is an area where fixing one issue regresses 10 others.
> 
> This code is used by `ls`, `rm`, `undo`, `legalhold ...`, `retention ...`, so I am a bit worried this can cause regressions there.

Thank you for your reply.
I suggest that we unify the display of command line execution results without distinguishing systems.
At the same time, we continue to support input ``\\``on the Windows system.

### Before modification on Windows host:
```
 ./mc.exe ls myminio
[2023-02-27 16:06:41 CST]     0B test\
[2023-02-27 16:17:11 CST]     0B test1\
[2023-02-27 16:17:42 CST]     0B test2\
```
### After modification on Windows host:
```
 ./mc.exe ls myminio
[2023-02-27 16:06:41 CST]     0B test/
[2023-02-27 16:17:11 CST]     0B test1/
[2023-02-27 16:17:42 CST]     0B test2/

$ ./mc.exe ls myminio\\test
[2023-02-27 16:07:11 CST]  34MiB STANDARD mc
[2023-02-27 19:29:56 CST]  34MiB STANDARD mc1
[2023-02-27 19:29:58 CST]  34MiB STANDARD mc2
[2023-02-27 19:30:00 CST]  34MiB STANDARD mc3

$ ./mc.exe ls myminio/test
[2023-02-27 16:07:11 CST]  34MiB STANDARD mc
[2023-02-27 19:29:56 CST]  34MiB STANDARD mc1
[2023-02-27 19:29:58 CST]  34MiB STANDARD mc2
[2023-02-27 19:30:00 CST]  34MiB STANDARD mc3
```
This can not only solve the #3509  problem, but also fix the problem that stat not work on windows.

I have fully verified other commands, please review my pr.

**Comment by klauspost** [comment]
@dormanze Could you check if #4503 also fixes the issues you observed?

Purely from a risk perspective I would prefer that.

**Comment by dormanze** [comment]
> @dormanze Could you check if #4503 also fixes the issues you observed?
> 
> Purely from a risk perspective I would prefer that.
Thank you for your reply.
Yes, from the point of view of risk, your modification solution is low risk and can solve the problem. I'll undo my pr.

**Pull request closed without merging**
