### PR TITLE
Update mc docs with MC_HOSTS env variable

### PR DESCRIPTION
**Pull request by Colhodm**

### CODE REVIEW

**Comment by kannappanr** [comment]
@Colhodm Please fix the Travis build issue.

**Comment by deekoder** [comment]
@Colhodm 
```
ocs/minio-client-complete-guide.md:153:12: "Enviroment" is a misspelling of "Environment"
docs/minio-client-complete-guide.md:157:52: "enviroment" is a misspelling of "environment"
docs/minio-client-complete-guide.md:153:12: "Enviroment" is a misspelling of "Environment"
docs/minio-client-complete-guide.md:157:52: "enviroment" is a misspelling of "environment"
```

**Comment by ebozduman** [comment]
@Colhodm 
It is also a good idea to squash all 4 commits.

**Comment by deekoder** [comment]
```
### Specify AccessKey and SecretKey through environment variables 
```
environment sounds better than environmental ;)

**Comment by ebozduman** [comment]
@deekoder :
I agree.

**Comment by harshavardhana** [comment]
Looks like there is another PR #2450

**Comment by deekoder** [comment]
closing this pr since there's a newer one.

**Pull request closed without merging**
