### PR TITLE
Fix admin-info, admin-status json status field

### LINKED ISSUE #2280: Wrong status message when doing `mc admin info minio --json`
## Expected behaviour
Minio in distributed mode - when running `mc admin info minio --json` and one node is down, the `status` should not be `success` for that one.

## Actual behaviour
Even if I have `error` field populated, the `status` is still success (the output is for a 3-node cluster):
{"status":"success","service":true,"address":"minio2:9000","error":"","storage":{"total":167720767488,"free":132576399360,"backend":{"backendType":"Erasure","onlineDisks":6,"offlineDisks":0}},"network":{"transferred":94864,"received":56830},"server":{"uptime":573347137993,"version":"2017-10-10T08:49:44Z","commitID":"60cc6184d253efee4a3120683517028342229e21","region":"","sqsARN":null}}
{"status":"success","service":true,"address":"minio0:9000","error":"dial-http minio0:9000/minio/admin: dial tcp: lookup minio0 on 127.0.0.11:53: server misbehaving"}
{"status":"success","service":true,"address":"minio1:9000","error":"","storage":{"total":167720767488,"free":132576399360,"backend":{"backendType":"Erasure","onlineDisks":6,"offlineDisks":0}},"network":{"transferred":783631,"received":355252},"server":{"uptime":8682093371814,"version":"2017-10-10T08:49:44Z","commitID":"60cc6184d253efee4a3120683517028342229e21","region":"","sqsARN":null}}

## Steps to reproduce the behaviour
1. Using docker-compose, declare 3 minio instances
2. Bring up the cluster (using docker-compose up)
3. Stop a docker container
4. Do a `mc admin info minio --json` and check the output.
## mc version
Version: 2017-10-10T08:50:07Z
Release-tag: DEVELOPMENT.2017-10-10T08-50-07Z
Commit-id: c10b429dcbeb7071e2758233afeda46d2ed688e5

### PR DESCRIPTION
**Pull request by krisis**
Fixes #2280

### CODE REVIEW

**Comment by vadmeste** [comment]
Emm, I thought about this use case before, and I said that the status should be `success` because we are able to gather information about all nodes. Now, if we want to know if a specific node is up or down, the user can parse the json data to search for that text.

**Comment by vadmeste** [comment]
I discussed with @krisis and I got what I was missing.. but I really think that we need to review this with @abperiasamy since it is a change in the API and I really don't get the purpose of Service field here.

**Comment by nitisht** [comment]
Blocked till this is discussed with @abperiasamy

**Comment by kannappanr** [comment]
@vadmeste Can you please update the minutes of discussion regarding this PR?

**Comment by vadmeste** [comment]
> @vadmeste Can you please update the minutes of discussion regarding this PR?

'service' doesn't need to be boolean but 'on' and 'off' instead.

**Comment by harshavardhana** [comment]
Can this PR be refactored with new admin API change? @krisis

**Comment by krisis** [comment]
@vadmeste I have updated the PR as described here - https://github.com/minio/mc/pull/2293#issuecomment-355772077

**Pull request merged**
