### PR TITLE
mirror: For non-s3 make sure we copy and exit properly.

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
Fixes #1996

**Comment by vadmeste** [comment]
:+1: for removing graceful shutdown.

However, doing mirroring in two phases can miss some objects uploaded during mirroring and before starting to watch because prepareMirrorURLs() can miss them.

**Comment by harshavardhana** [comment]
That was intentional @vadmeste we don't need to do that.

**Comment by harshavardhana** [comment]
> However, doing mirroring in two phases can miss some objects uploaded during mirroring and before starting to watch because prepareMirrorURLs() can miss them.

Done added @vadmeste

**Pull request merged**
