### PR TITLE
new option --delete-transferred for mc copy

### PR DESCRIPTION
**Pull request by gitnchez**
option to allow remove local files uploaded to remote storage

### CODE REVIEW

**Comment by kannappanr** [comment]
@gitnchez Thanks for this PR. We need to discuss internally and see if we can take this in. I will get back 
 with what we decide.

**Comment by harshavardhana** [comment]
@deekoder did we agree on this ?

**Comment by harshavardhana** [comment]
I think this option is not useful @gitnchez you can do `mc cp` and `mc rm` locally which would serve the same functionality.

**Comment by gitnchez** [comment]
I need it in one case - when i copy multiple files via mc from one folder
to minio server and there are multiple writes to this folder at the same
time. Maybe we need one separate command, something like "mc mv" for such
cases?

пт, 8 мар. 2019 г. в 01:34, Harshavardhana <notifications@github.com>:

**Comment by harshavardhana** [comment]
`mc mv` might be a better idea

**Comment by kannappanr** [comment]
ping @gitnchez Can you please make this change suggested here?

**Comment by gitnchez** [comment]
> ping @gitnchez Can you please make this change suggested here?

sorry, i do not have enough experience for this

**Comment by harshavardhana** [comment]
Closing this PR as stale, please re-open with a completed fix.

**Pull request closed without merging**
